import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import {PrismaService} from '../common/prisma.service';
import {AuditService} from '../common/audit.service';
import {CreateProjectDto,CreateTaskDto,UpdateProjectDto,UpdateTaskDto} from './projects.dto';

@Injectable()
export class ProjectsService {
 constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
 private async customer(org:string,id?:string){if(!id)return;const c=await this.prisma.customer.findFirst({where:{id,organizationId:org}});if(!c)throw new BadRequestException('Client introuvable dans cette organisation.');}
 private async project(org:string,id:string){const p=await this.prisma.project.findFirst({where:{id,organizationId:org}});if(!p)throw new NotFoundException('Projet introuvable.');return p;}
 async list(org:string){const projects=await this.prisma.project.findMany({where:{organizationId:org},include:{customer:true,tasks:true,expenses:true,invoices:true},orderBy:{updatedAt:'desc'}});return projects.map(p=>this.metrics(p));}
 async get(org:string,id:string){const p=await this.prisma.project.findFirst({where:{id,organizationId:org},include:{customer:true,tasks:{include:{project:true}},expenses:{include:{supplier:true}},invoices:{include:{customer:true}}}});if(!p)throw new NotFoundException('Projet introuvable.');return this.metrics(p);}
 private metrics(p:any){const revenue=p.invoices.filter((i:any)=>i.status!=='CANCELLED').reduce((s:number,i:any)=>s+Number(i.total),0);const actualCost=p.expenses.filter((e:any)=>e.status==='PAID').reduce((s:number,e:any)=>s+Number(e.amount),0);const committedCost=p.expenses.filter((e:any)=>['APPROVED','PAID'].includes(e.status)).reduce((s:number,e:any)=>s+Number(e.amount),0);const done=p.tasks.filter((t:any)=>t.status==='DONE').length;const progress=p.tasks.length?Math.round(done/p.tasks.length*100):0;const budget=p.budget==null?null:Number(p.budget);return {...p,revenue,actualCost,committedCost,margin:revenue-actualCost,marginRate:revenue?((revenue-actualCost)/revenue)*100:null,budgetVariance:budget==null?null:budget-actualCost,progress};}
 async create(org:string,userId:string,dto:CreateProjectDto,request:any){await this.customer(org,dto.customerId);const p=await this.prisma.project.create({data:{organizationId:org,name:dto.name.trim(),customerId:dto.customerId,budget:dto.budget,status:dto.status||'ACTIVE'}});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'Project',entityId:p.id,next:p,ip:request.ip,userAgent:request.headers['user-agent']});return p;}
 async update(org:string,userId:string,id:string,dto:UpdateProjectDto,request:any){const old=await this.project(org,id);if(dto.customerId!==undefined)await this.customer(org,dto.customerId);const p=await this.prisma.project.update({where:{id},data:{name:dto.name?.trim(),customerId:dto.customerId,budget:dto.budget,status:dto.status}});await this.audit.record({organizationId:org,userId,action:'UPDATE',entity:'Project',entityId:id,previous:old,next:p,ip:request.ip,userAgent:request.headers['user-agent']});return p;}
 async tasks(org:string,projectId?:string){return this.prisma.task.findMany({where:{organizationId:org,...(projectId?{projectId}:{})},include:{project:true,organization:true},orderBy:[{dueAt:'asc'},{createdAt:'desc'}]});}
 async createTask(org:string,userId:string,dto:CreateTaskDto,request:any){if(dto.projectId)await this.project(org,dto.projectId);if(dto.assigneeId){const u=await this.prisma.user.findFirst({where:{id:dto.assigneeId,memberships:{some:{organizationId:org}}}});if(!u)throw new BadRequestException('Collaborateur introuvable.');}const t=await this.prisma.task.create({data:{organizationId:org,title:dto.title.trim(),projectId:dto.projectId,status:dto.status||'TODO',dueAt:dto.dueAt?new Date(dto.dueAt):undefined,assigneeId:dto.assigneeId}});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'Task',entityId:t.id,next:t,ip:request.ip,userAgent:request.headers['user-agent']});return t;}
 async updateTask(org:string,userId:string,id:string,dto:UpdateTaskDto,request:any){const old=await this.prisma.task.findFirst({where:{id,organizationId:org}});if(!old)throw new NotFoundException('Tâche introuvable.');if(dto.projectId!==undefined&&dto.projectId)await this.project(org,dto.projectId);if(dto.assigneeId){const u=await this.prisma.user.findFirst({where:{id:dto.assigneeId,memberships:{some:{organizationId:org}}}});if(!u)throw new BadRequestException('Collaborateur introuvable.');}const t=await this.prisma.task.update({where:{id},data:{title:dto.title?.trim(),status:dto.status,dueAt:dto.dueAt?new Date(dto.dueAt):undefined,assigneeId:dto.assigneeId,projectId:dto.projectId}});await this.audit.record({organizationId:org,userId,action:'UPDATE',entity:'Task',entityId:id,previous:old,next:t,ip:request.ip,userAgent:request.headers['user-agent']});return t;}
 async profitability(org:string){const projects=await this.list(org);return {projects,totals:{revenue:projects.reduce((s:number,p:any)=>s+p.revenue,0),actualCost:projects.reduce((s:number,p:any)=>s+p.actualCost,0),margin:projects.reduce((s:number,p:any)=>s+p.margin,0),budget:projects.reduce((s:number,p:any)=>s+(p.budget||0),0)}};}
}
