import {ConflictException,Injectable,UnauthorizedException} from '@nestjs/common';
import {PrismaService} from '../common/prisma.service';
import {createToken,hashPassword,hashToken,verifyPassword} from '../common/security/password';
import {LoginDto,RegisterDto} from './auth.dto';
const SESSION_DAYS=30;
@Injectable() export class AuthService{constructor(private readonly prisma:PrismaService){}
 async register(dto:RegisterDto){const email=dto.email.trim().toLowerCase();const existing=await this.prisma.user.findUnique({where:{email}});if(existing)throw new ConflictException('Email already registered');const slug=dto.organizationName.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+createToken().slice(0,6);const passwordHash=await hashPassword(dto.password);const token=createToken();const user=await this.prisma.user.create({data:{email,name:dto.name.trim(),passwordHash,memberships:{create:{role:'OWNER',organization:{create:{name:dto.organizationName.trim(),slug}}}}},include:{memberships:{include:{organization:true}}}});const session=await this.createSession(user.id);return {sessionToken:session.raw,user:{id:user.id,email:user.email,name:user.name},organizations:user.memberships.map(m=>({id:m.organizationId,name:m.organization.name,role:m.role}))}}
 async login(dto:LoginDto){const user=await this.prisma.user.findUnique({where:{email:dto.email.trim().toLowerCase()},include:{memberships:{include:{organization:true}}}});if(!user?.passwordHash||!(await verifyPassword(dto.password,user.passwordHash)))throw new UnauthorizedException('Invalid email or password');const session=await this.createSession(user.id);return {sessionToken:session.raw,user:{id:user.id,email:user.email,name:user.name},organizations:user.memberships.map(m=>({id:m.organizationId,name:m.organization.name,role:m.role}))}}
 async createSession(userId:string){const raw=createToken();const expiresAt=new Date(Date.now()+SESSION_DAYS*86400000);const session=await this.prisma.session.create({data:{userId,tokenHash:hashToken(raw),expiresAt}});return {raw,id:session.id,expiresAt}}
 async getSession(raw?:string){if(!raw)return null;const session=await this.prisma.session.findUnique({where:{tokenHash:hashToken(raw)},include:{user:{include:{memberships:true}}}});if(!session||session.expiresAt<=new Date()){if(session)await this.prisma.session.delete({where:{id:session.id}});return null}await this.prisma.session.update({where:{id:session.id},data:{lastSeenAt:new Date()}});return session}
 async logout(raw?:string){if(raw)await this.prisma.session.deleteMany({where:{tokenHash:hashToken(raw)}});return {ok:true}}
}
