import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import {Prisma,PrismaClient} from '@prisma/client';
import {PrismaService} from '../common/prisma.service';
import {AuditService} from '../common/audit.service';
import {CreateInvoiceDto,CreatePaymentDto,CreateQuoteDto,QuoteItemDto} from './sales.dto';
import {InventoryService} from '../inventory/inventory.service';

@Injectable()
export class SalesService{
 constructor(private readonly prisma:PrismaService,private readonly audit:AuditService,private readonly inventory:InventoryService){}
 private money(v:number){return Math.round((v+Number.EPSILON)*100)/100}
 private calculate(items:QuoteItemDto[],discount=0){
  if(!items?.length) throw new BadRequestException('Au moins une ligne est requise.');
  const normalized=items.map(i=>{const quantity=Number(i.quantity),unitPrice=Number(i.unitPrice),taxRate=i.taxRate==null?20:Number(i.taxRate);if(!i.description.trim())throw new BadRequestException('La description est requise.');const lineSubtotal=this.money(quantity*unitPrice);const lineTax=this.money(lineSubtotal*taxRate/100);return {...i,quantity,unitPrice,taxRate,lineSubtotal,lineTax,lineTotal:this.money(lineSubtotal+lineTax)}});
  const subtotal=this.money(normalized.reduce((s,i)=>s+i.lineSubtotal,0)); const safeDiscount=this.money(Math.min(Math.max(Number(discount||0),0),subtotal));
  const taxable=this.money(subtotal-safeDiscount); const tax=this.money(normalized.reduce((s,i)=>s+i.lineTax,0)*(taxable/subtotal||0)); const total=this.money(taxable+tax);
  return {items:normalized,subtotal,discount:safeDiscount,tax,total};
 }
 private async nextNumber(tx:PrismaClient|Prisma.TransactionClient,organizationId:string,type:'QUOTE'|'INVOICE'){
  const year=new Date().getFullYear();
  const existing=await tx.numberSequence.findUnique({where:{organizationId_type_year:{organizationId,type,year}}});
  if(!existing){await tx.numberSequence.create({data:{organizationId,type,year,nextValue:2}});return `${type==='QUOTE'?'DEV':'INV'}-${year}-0001`;}
  const n=existing.nextValue; await tx.numberSequence.update({where:{id:existing.id},data:{nextValue:{increment:1}}}); return `${type==='QUOTE'?'DEV':'INV'}-${year}-${String(n).padStart(4,'0')}`;
 }
 private async productSnapshot(organizationId:string,item:QuoteItemDto){if(!item.productId)return item;const p=await this.prisma.product.findFirst({where:{id:item.productId,organizationId,active:true}});if(!p)throw new BadRequestException('Produit ou service introuvable.');return {...item,description:item.description?.trim()||p.name,unitPrice:item.unitPrice??Number(p.sellingPrice),taxRate:item.taxRate??Number(p.taxRate)};}
 private async customerExists(organizationId:string,id:string){const c=await this.prisma.customer.findFirst({where:{id,organizationId}});if(!c)throw new BadRequestException('Client introuvable dans cette organisation.');return c}
 async quotes(organizationId:string,status?:string){return this.prisma.quote.findMany({where:{organizationId,...(status?{status:status as any}:{})},include:{customer:true,items:{include:{product:true}}},orderBy:{createdAt:'desc'}})}
 async quote(organizationId:string,id:string){const q=await this.prisma.quote.findFirst({where:{id,organizationId},include:{customer:true,items:{include:{product:true}},invoices:true}});if(!q)throw new NotFoundException('Devis introuvable.');return q}
 async createQuote(organizationId:string,userId:string,dto:CreateQuoteDto,request:any){await this.customerExists(organizationId,dto.customerId);if(dto.projectId){const p=await this.prisma.project.findFirst({where:{id:dto.projectId,organizationId}});if(!p)throw new BadRequestException('Projet introuvable.');}const items=await Promise.all(dto.items.map(i=>this.productSnapshot(organizationId,i)));const c=this.calculate(items,dto.discount);const q=await this.prisma.$transaction(async tx=>{const number=await this.nextNumber(tx,organizationId,'QUOTE');return tx.quote.create({data:{organizationId,customerId:dto.customerId,projectId:dto.projectId,number,status:'DRAFT',subtotal:c.subtotal,discount:c.discount,tax:c.tax,total:c.total,validUntil:dto.validUntil?new Date(dto.validUntil):undefined,notes:dto.notes?.trim(),items:{create:c.items.map(i=>({productId:i.productId||undefined,description:i.description.trim(),quantity:i.quantity,unitPrice:i.unitPrice,taxRate:i.taxRate,lineSubtotal:i.lineSubtotal,lineTax:i.lineTax,lineTotal:i.lineTotal}))}},include:{customer:true,items:{include:{product:true}}}})});await this.audit.record({organizationId,userId,action:'CREATE',entity:'Quote',entityId:q.id,next:q,ip:request.ip,userAgent:request.headers['user-agent']});return q}
 async sendQuote(organizationId:string,userId:string,id:string,request:any){const q=await this.quote(organizationId,id);if(!['DRAFT','REJECTED'].includes(q.status))throw new BadRequestException('Ce devis ne peut pas être envoyé dans son état actuel.');const updated=await this.prisma.quote.update({where:{id},data:{status:'SENT',issuedAt:new Date()}});await this.audit.record({organizationId,userId,action:'SEND',entity:'Quote',entityId:id,previous:q,next:updated,ip:request.ip,userAgent:request.headers['user-agent']});return updated}
 async convertQuote(organizationId:string,userId:string,id:string,request:any){const q=await this.quote(organizationId,id);if(!['SENT','ACCEPTED'].includes(q.status))throw new BadRequestException('Le devis doit être envoyé ou accepté avant conversion.');const existing=q.invoices[0];if(existing)return existing;const invoice=await this.prisma.$transaction(async tx=>{const number=await this.nextNumber(tx,organizationId,'INVOICE');const inv=await tx.invoice.create({data:{organizationId,customerId:q.customerId,projectId:q.projectId,number,status:'DRAFT',subtotal:q.subtotal,discount:q.discount,tax:q.tax,total:q.total,notes:q.notes,items:{create:q.items.map(i=>({productId:i.productId||undefined,description:i.description,quantity:i.quantity,unitPrice:i.unitPrice,taxRate:i.taxRate,lineSubtotal:i.lineSubtotal,lineTax:i.lineTax,lineTotal:i.lineTotal}))}},include:{customer:true,items:{include:{product:true}}}});await tx.quote.update({where:{id:q.id},data:{status:'CONVERTED'}});return inv});await this.audit.record({organizationId,userId,action:'CONVERT',entity:'Quote',entityId:id,previous:q,next:invoice,ip:request.ip,userAgent:request.headers['user-agent']});return invoice}
 async invoices(organizationId:string,status?:string){const rows=await this.prisma.invoice.findMany({where:{organizationId,...(status?{status:status as any}:{})},include:{customer:true,items:{include:{product:true}},payments:true},orderBy:{createdAt:'desc'}});return rows.map(i=>({...i,status:i.status==='SENT'&&i.dueAt&&new Date(i.dueAt)<new Date()?'OVERDUE':i.status,paid:i.payments.reduce((s,p)=>s+Number(p.amount),0),balance:this.money(Number(i.total)-i.payments.reduce((s,p)=>s+Number(p.amount),0))}))}
 async invoice(organizationId:string,id:string){const i=await this.prisma.invoice.findFirst({where:{id,organizationId},include:{customer:true,items:{include:{product:true}},payments:true,quote:true}});if(!i)throw new NotFoundException('Facture introuvable.');return i}
 async createInvoice(organizationId:string,userId:string,dto:CreateInvoiceDto,request:any){await this.customerExists(organizationId,dto.customerId);const items=await Promise.all(dto.items.map(i=>this.productSnapshot(organizationId,i)));if(dto.quoteId){const q=await this.prisma.quote.findFirst({where:{id:dto.quoteId,organizationId}});if(!q)throw new BadRequestException('Devis introuvable.');} if(dto.projectId){const p=await this.prisma.project.findFirst({where:{id:dto.projectId,organizationId}});if(!p)throw new BadRequestException('Projet introuvable.');}const c=this.calculate(items,dto.discount);const inv=await this.prisma.$transaction(async tx=>{const number=await this.nextNumber(tx,organizationId,'INVOICE');return tx.invoice.create({data:{organizationId,customerId:dto.customerId,projectId:dto.projectId,quoteId:dto.quoteId,warehouseId:dto.warehouseId,number,status:'DRAFT',subtotal:c.subtotal,discount:c.discount,tax:c.tax,total:c.total,dueAt:dto.dueAt?new Date(dto.dueAt):undefined,issuedAt:dto.issuedAt?new Date(dto.issuedAt):undefined,notes:dto.notes?.trim(),items:{create:c.items.map(i=>({productId:i.productId||undefined,description:i.description.trim(),quantity:i.quantity,unitPrice:i.unitPrice,taxRate:i.taxRate,lineSubtotal:i.lineSubtotal,lineTax:i.lineTax,lineTotal:i.lineTotal}))}},include:{customer:true,items:{include:{product:true}}}})});await this.audit.record({organizationId,userId,action:'CREATE',entity:'Invoice',entityId:inv.id,next:inv,ip:request.ip,userAgent:request.headers['user-agent']});return inv}
 async sendInvoice(organizationId:string,userId:string,id:string,request:any){const i=await this.invoice(organizationId,id);if(!['DRAFT'].includes(i.status))throw new BadRequestException('Cette facture ne peut pas être envoyée dans son état actuel.');const updated=await this.prisma.$transaction(async tx=>{const posted=await this.inventory.postInvoice(tx,organizationId,id);return tx.invoice.update({where:{id},data:{status:'SENT',issuedAt:i.issuedAt??new Date(),warehouseId:posted.warehouseId,stockPostedAt:posted.stockPostedAt}})});await this.audit.record({organizationId,userId,action:'SEND',entity:'Invoice',entityId:id,previous:i,next:updated,ip:request.ip,userAgent:request.headers['user-agent']});return updated}
 async cancelInvoice(organizationId:string,userId:string,id:string,request:any){const i=await this.invoice(organizationId,id);if(['PAID','CANCELLED'].includes(i.status))throw new BadRequestException('Cette facture ne peut pas être annulée.');const updated=await this.prisma.$transaction(async tx=>{await this.inventory.reverseInvoice(tx,organizationId,id);return tx.invoice.update({where:{id},data:{status:'CANCELLED'}})});await this.audit.record({organizationId,userId,action:'CANCEL',entity:'Invoice',entityId:id,previous:i,next:updated,ip:request.ip,userAgent:request.headers['user-agent']});return updated}
 async payments(organizationId:string){return this.prisma.payment.findMany({where:{organizationId},include:{invoice:{include:{customer:true}}},orderBy:{paidAt:'desc'}})}
 async createPayment(organizationId:string,userId:string,dto:CreatePaymentDto,request:any){const invoice=await this.invoice(organizationId,dto.invoiceId);if(['CANCELLED'].includes(invoice.status))throw new BadRequestException('Impossible d\'enregistrer un paiement sur une facture annulée.');const paid=invoice.payments.reduce((s,p)=>s+Number(p.amount),0);const balance=this.money(Number(invoice.total)-paid);if(dto.amount>balance+0.001)throw new BadRequestException(`Le paiement dépasse le solde restant de ${balance.toFixed(2)} MAD.`);const payment=await this.prisma.$transaction(async tx=>{const p=await tx.payment.create({data:{organizationId,invoiceId:dto.invoiceId,amount:dto.amount,paidAt:dto.paidAt?new Date(dto.paidAt):new Date(),method:dto.method?.trim(),reference:dto.reference?.trim()}});const newPaid=paid+dto.amount;await tx.invoice.update({where:{id:invoice.id},data:{status:newPaid>=Number(invoice.total)-0.001?'PAID':'PARTIALLY_PAID'}});return p});await this.audit.record({organizationId,userId,action:'CREATE',entity:'Payment',entityId:payment.id,next:payment,ip:request.ip,userAgent:request.headers['user-agent']});return payment}
}
