'use client';
import {apiFetch,getOrganizationId} from '../../../lib/api-client';
import {FormEvent,useEffect,useState} from 'react';
type Customer={id:string;name:string}; type Invoice={id:string;number:string;customer?:Customer;total:number;balance:number;paid:number;status:string;dueAt?:string;issuedAt?:string};
export default function InvoicesPage(){
 const [rows,setRows]=useState<Invoice[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[customerId,setCustomerId]=useState(''),[description,setDescription]=useState(''),[unitPrice,setUnitPrice]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);const org=getOrganizationId()||'';const h={'x-organization-id':org};const [a,b]=await Promise.all([apiFetch('/invoices',{credentials:'include',headers:h}),apiFetch('/customers',{credentials:'include',headers:h})]);if(!a.ok||!b.ok){setError('Impossible de charger les données de facturation.');setRows([])}else{setRows(await a.json());const d=await b.json();setCustomers(Array.isArray(d)?d:d.items||[])}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();if(!customerId||!description||!unitPrice)return;const org=getOrganizationId()||'';const r=await apiFetch('/invoices',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org},body:JSON.stringify({customerId,items:[{description,quantity:1,unitPrice:Number(unitPrice),taxRate:20}]})});if(!r.ok){setError('Création de facture impossible.');return}setDescription('');setUnitPrice('');load()}
 async function pay(inv:Invoice){if(inv.balance<=0)return;const org=getOrganizationId()||'';const r=await apiFetch('/payments',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org},body:JSON.stringify({invoiceId:inv.id,amount:inv.balance,method:'BANK'})});if(!r.ok)setError('Paiement impossible.');else load()}
 const total=rows.reduce((s,x)=>s+Number(x.total||0),0),balance=rows.reduce((s,x)=>s+Number(x.balance||0),0);
 return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Factures</h1><p className="text-sm text-gray-500">Facturation et encaissements de l’organisation active.</p></div><form onSubmit={create} className="grid md:grid-cols-4 gap-2 bg-white border rounded-xl p-4"><select required value={customerId} onChange={e=>setCustomerId(e.target.value)} className="border rounded-lg px-3 py-2"><option value="">Client</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" className="border rounded-lg px-3 py-2"/><input required min="0" step="0.01" type="number" value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} placeholder="Prix HT" className="border rounded-lg px-3 py-2"/><button className="rounded-lg bg-[var(--primary)] text-white px-4 py-2">Créer</button></form>{error&&<div className="text-sm text-red-600">{error}</div>}<div className="grid md:grid-cols-2 gap-4"><div className="bg-white border rounded-xl p-4"><div className="text-sm text-gray-500">Total facturé</div><div className="text-2xl font-bold">{total.toLocaleString('fr-MA')} MAD</div></div><div className="bg-white border rounded-xl p-4"><div className="text-sm text-gray-500">Créances</div><div className="text-2xl font-bold">{balance.toLocaleString('fr-MA')} MAD</div></div></div><div className="bg-white border rounded-xl overflow-hidden">{loading?<div className="p-8 text-center text-gray-500">Chargement…</div>:rows.length===0?<div className="p-8 text-center text-gray-500">Aucune facture.</div>:<table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">N°</th><th className="p-3 text-left">Client</th><th className="p-3 text-right">Total</th><th className="p-3 text-right">Solde</th><th className="p-3 text-left">Statut</th><th className="p-3"/></tr></thead><tbody>{rows.map(i=><tr key={i.id} className="border-t"><td className="p-3 font-medium">{i.number}</td><td className="p-3">{i.customer?.name||'—'}</td><td className="p-3 text-right">{Number(i.total).toLocaleString('fr-MA')} MAD</td><td className="p-3 text-right">{Number(i.balance).toLocaleString('fr-MA')} MAD</td><td className="p-3">{i.status}</td><td className="p-3 text-right">{i.balance>0&&<button onClick={()=>pay(i)} className="rounded-lg border px-3 py-1.5">Enregistrer paiement</button>}</td></tr>)}</tbody></table>}</div></section>
}