'use client';
import {apiFetch,getOrganizationId,setOrganizationId} from '../../../lib/api-client';
import {FormEvent,useEffect,useState} from 'react';
type Customer={id:string;name:string}; type Quote={id:string;number:string;customer?:Customer;total:number;status:string;createdAt?:string};
export default function QuotesPage(){
 const [rows,setRows]=useState<Quote[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[customerId,setCustomerId]=useState(''),[description,setDescription]=useState(''),[unitPrice,setUnitPrice]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){const org=getOrganizationId()||'';const h={'x-organization-id':org};const [q,c]=await Promise.all([apiFetch(+'/quotes',{credentials:'include',headers:h}),apiFetch(+'/customers',{credentials:'include',headers:h})]);if(!q.ok||!c.ok){setError('Impossible de charger les données.');setRows([])}else{setRows(await q.json());const cd=await c.json();setCustomers(Array.isArray(cd)?cd:cd.items||[])}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();if(!customerId||!description||!unitPrice)return;const org=getOrganizationId()||'';const r=await apiFetch(+'/quotes',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org},body:JSON.stringify({customerId,items:[{description,quantity:1,unitPrice:Number(unitPrice),taxRate:20}]})});if(!r.ok){setError('Création du devis impossible.');return}setDescription('');setUnitPrice('');load()}
 return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Devis</h1><p className="text-sm text-gray-500">Devis tenant-scoped depuis l’API de vente.</p></div><form onSubmit={create} className="grid md:grid-cols-4 gap-2 bg-white border rounded-xl p-4"><select required value={customerId} onChange={e=>setCustomerId(e.target.value)} className="border rounded-lg px-3 py-2"><option value="">Client</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" className="border rounded-lg px-3 py-2"/><input required min="0" step="0.01" type="number" value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} placeholder="Prix HT" className="border rounded-lg px-3 py-2"/><button className="rounded-lg bg-[var(--primary)] text-white px-4 py-2">Créer</button></form>{error&&<div className="text-sm text-red-600">{error}</div>}<div className="bg-white border rounded-xl overflow-hidden">{loading?<div className="p-8 text-center text-gray-500">Chargement…</div>:rows.length===0?<div className="p-8 text-center text-gray-500">Aucun devis.</div>:<table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">N°</th><th className="p-3 text-left">Client</th><th className="p-3 text-right">Total</th><th className="p-3 text-left">Statut</th></tr></thead><tbody>{rows.map(q=><tr key={q.id} className="border-t"><td className="p-3 font-medium">{q.number}</td><td className="p-3">{q.customer?.name||'—'}</td><td className="p-3 text-right">{Number(q.total).toLocaleString('fr-MA')} MAD</td><td className="p-3">{q.status}</td></tr>)}</tbody></table>}</div></section>
}