import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import {Prisma,PrismaClient} from '@prisma/client';
import {PrismaService} from '../common/prisma.service';
import {AuditService} from '../common/audit.service';
import {CreateAccountDto,CreateCashAccountDto,CashTransactionDto,ManualJournalDto} from './finance.dto';

@Injectable()
export class FinanceService {
 constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
 private money(n:number){return Math.round((n+Number.EPSILON)*100)/100}
 private async account(tx:PrismaClient|Prisma.TransactionClient,org:string,code:string){const a=await tx.account.findFirst({where:{organizationId:org,code,active:true}});if(!a)throw new BadRequestException(`Compte ${code} introuvable.`);return a}
 private async nextNumber(tx:PrismaClient|Prisma.TransactionClient,org:string){const year=new Date().getFullYear();const code=`JE-${year}-`;const last=await tx.journalEntry.findFirst({where:{organizationId:org,number:{startsWith:code}},orderBy:{number:'desc'}});const n=last?Number(last.number.slice(-4))+1:1;return `${code}${String(n).padStart(4,'0')}`}
 async seedChart(org:string,userId:string){const defaults=[['101000','Capital','EQUITY'],['411000','Clients','ASSET'],['445710','TVA collectée','LIABILITY'],['512000','Banque','ASSET'],['530000','Caisse','ASSET'],['701000','Ventes de marchandises','REVENUE'],['706000','Prestations de services','REVENUE'],['613000','Achats et charges externes','EXPENSE'],['445660','TVA déductible','ASSET'],['401000','Fournisseurs','LIABILITY']];let created=0;for(const [code,name,type] of defaults){const r=await this.prisma.account.upsert({where:{organizationId_code:{organizationId:org,code}},update:{},create:{organizationId:org,code,name,type:type as any}});if(r.createdAt.getTime()===r.updatedAt.getTime())created++}await this.audit.record({organizationId:org,userId,action:'SEED_CHART',entity:'Account',next:{created}});return this.accounts(org)}
 async accounts(org:string){return this.prisma.account.findMany({where:{organizationId:org},orderBy:{code:'asc'}})}
 async createAccount(org:string,userId:string,dto:CreateAccountDto,request:any){const exists=await this.prisma.account.findFirst({where:{organizationId:org,code:dto.code}});if(exists)throw new BadRequestException('Ce code comptable existe déjà.');const a=await this.prisma.account.create({data:{organizationId:org,code:dto.code,name:dto.name.trim(),type:dto.type,parentId:dto.parentId}});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'Account',entityId:a.id,next:a,ip:request.ip,userAgent:request.headers['user-agent']});return a}
 async cashAccounts(org:string){return this.prisma.cashAccount.findMany({where:{organizationId:org,active:true},include:{account:true},orderBy:{name:'asc'}})}
 async createCashAccount(org:string,userId:string,dto:CreateCashAccountDto,request:any){const account=dto.accountId?await this.prisma.account.findFirst({where:{id:dto.accountId,organizationId:org,type:'ASSET'}}):await this.account(this.prisma,org,dto.type==='BANK'?'512000':'530000');if(!account)throw new BadRequestException('Compte de trésorerie invalide.');const c=await this.prisma.cashAccount.create({data:{organizationId:org,accountId:account.id,name:dto.name.trim(),type:dto.type,currency:dto.currency||'MAD',openingBalance:dto.openingBalance||0}});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'CashAccount',entityId:c.id,next:c,ip:request.ip,userAgent:request.headers['user-agent']});return c}
 async cashTransactions(org:string){return this.prisma.cashTransaction.findMany({where:{organizationId:org},include:{cashAccount:true},orderBy:{transactionDate:'desc'}})}
 async addCashTransaction(org:string,userId:string,dto:CashTransactionDto,request:any){const c=await this.prisma.cashAccount.findFirst({where:{id:dto.cashAccountId,organizationId:org,active:true}});if(!c)throw new BadRequestException('Compte de trésorerie introuvable.');const row=await this.prisma.cashTransaction.create({data:{organizationId:org,cashAccountId:c.id,type:dto.type,amount:dto.amount,transactionDate:dto.transactionDate?new Date(dto.transactionDate):new Date(),description:dto.description?.trim(),reference:dto.reference?.trim()}});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'CashTransaction',entityId:row.id,next:row,ip:request.ip,userAgent:request.headers['user-agent']});return row}
 async postManual(org:string,userId:string,dto:ManualJournalDto,request:any){if(dto.lines.length<2)throw new BadRequestException('Une écriture doit contenir au moins deux lignes.');const debit=this.money(dto.lines.reduce((s,l)=>s+Number(l.debit||0),0));const credit=this.money(dto.lines.reduce((s,l)=>s+Number(l.credit||0),0));if(debit<=0||Math.abs(debit-credit)>0.001)throw new BadRequestException('Les débits et crédits doivent être égaux et supérieurs à zéro.');const entry=await this.prisma.$transaction(async tx=>{const number=await this.nextNumber(tx,org);const lines=[];for(const l of dto.lines){const a=await this.account(tx,org,l.accountCode);if((l.debit>0&&l.credit>0)||(l.debit===0&&l.credit===0))throw new BadRequestException('Chaque ligne doit avoir soit un débit soit un crédit.');lines.push({accountId:a.id,debit:l.debit,credit:l.credit,description:l.description})}return tx.journalEntry.create({data:{organizationId:org,number,entryDate:new Date(dto.entryDate),description:dto.description.trim(),sourceType:'MANUAL',lines:{create:lines}},include:{lines:{include:{account:true}}}})});await this.audit.record({organizationId:org,userId,action:'POST',entity:'JournalEntry',entityId:entry.id,next:entry,ip:request.ip,userAgent:request.headers['user-agent']});return entry}
 async postInvoice(org:string,userId:string,id:string,request:any){const inv=await this.prisma.invoice.findFirst({where:{id,organizationId:org},include:{items:{include:{product:true}}}});if(!inv)throw new NotFoundException('Facture introuvable.');const existing=await this.prisma.journalEntry.findFirst({where:{organizationId:org,sourceType:'SALES_INVOICE',sourceId:id}});if(existing)return existing;const ar=await this.account(this.prisma,org,'411000');const vat=await this.account(this.prisma,org,'445710');const revProduct=await this.account(this.prisma,org,'701000');const revService=await this.account(this.prisma,org,'706000');const productBase=inv.items.filter(i=>i.product?.type==='PRODUCT').reduce((s,i)=>s+Number(i.lineSubtotal),0);const serviceBase=Number(inv.subtotal)-productBase;const entry=await this.prisma.$transaction(async tx=>{const number=await this.nextNumber(tx,org);const lines:any[]=[{accountId:ar.id,debit:Number(inv.total),credit:0,description:`Facture ${inv.number}`}];if(productBase)lines.push({accountId:revProduct.id,debit:0,credit:this.money(productBase),description:`Ventes ${inv.number}`});if(serviceBase)lines.push({accountId:revService.id,debit:0,credit:this.money(serviceBase),description:`Prestations ${inv.number}`});if(Number(inv.tax))lines.push({accountId:vat.id,debit:0,credit:Number(inv.tax),description:`TVA ${inv.number}`});return tx.journalEntry.create({data:{organizationId:org,number,entryDate:inv.issuedAt||new Date(),description:`Facture client ${inv.number}`,sourceType:'SALES_INVOICE',sourceId:id,lines:{create:lines}},include:{lines:{include:{account:true}}}})});await this.audit.record({organizationId:org,userId,action:'POST',entity:'JournalEntry',entityId:entry.id,next:entry,ip:request.ip,userAgent:request.headers['user-agent']});return entry}
 async postPayment(org:string,userId:string,id:string,cashAccountId:string,request:any){const p=await this.prisma.payment.findFirst({where:{id,organizationId:org},include:{invoice:true}});if(!p)throw new NotFoundException('Paiement introuvable.');const existing=await this.prisma.journalEntry.findFirst({where:{organizationId:org,sourceType:'SALES_PAYMENT',sourceId:id}});if(existing)return existing;const c=await this.prisma.cashAccount.findFirst({where:{id:cashAccountId,organizationId:org,active:true},include:{account:true}});if(!c)throw new BadRequestException('Compte de trésorerie introuvable.');const ar=await this.account(this.prisma,org,'411000');const entry=await this.prisma.$transaction(async tx=>{const number=await this.nextNumber(tx,org);const j=await tx.journalEntry.create({data:{organizationId:org,number,entryDate:p.paidAt,description:`Paiement ${p.reference||p.id} - ${p.invoice.number}`,sourceType:'SALES_PAYMENT',sourceId:id,lines:{create:[{accountId:c.accountId,debit:Number(p.amount),credit:0},{accountId:ar.id,debit:0,credit:Number(p.amount)}]}}});await tx.cashTransaction.create({data:{organizationId:org,cashAccountId:c.id,type:'INCOME',amount:p.amount,transactionDate:p.paidAt,description:`Paiement facture ${p.invoice.number}`,sourceType:'SALES_PAYMENT',sourceId:id}});return j});return entry}
 async postExpense(org:string,userId:string,id:string,cashAccountId:string,request:any){const e=await this.prisma.expense.findFirst({where:{id,organizationId:org}});if(!e)throw new NotFoundException('Dépense introuvable.');if((e as any).status && (e as any).status!=='APPROVED')throw new BadRequestException('La dépense doit être approuvée avant comptabilisation.');const existing=await this.prisma.journalEntry.findFirst({where:{organizationId:org,sourceType:'EXPENSE',sourceId:id}});if(existing)return existing;const cash=await this.prisma.cashAccount.findFirst({where:{id:cashAccountId,organizationId:org,active:true}});if(!cash)throw new BadRequestException('Compte de trésorerie introuvable.');const exp=await this.account(this.prisma,org,e.accountCode||'613000');const entry=await this.prisma.$transaction(async tx=>{const number=await this.nextNumber(tx,org);const lines:any[]=[{accountId:exp.id,debit:Number((e as any).netAmount||e.amount),credit:0}];if(Number((e as any).taxAmount)>0){const vat=await this.account(tx,org,'445660');lines.push({accountId:vat.id,debit:Number((e as any).taxAmount),credit:0});}lines.push({accountId:cash.accountId,debit:0,credit:Number(e.amount)});const j=await tx.journalEntry.create({data:{organizationId:org,number,entryDate:e.incurredAt,description:e.description||`Dépense ${e.category}`,sourceType:'EXPENSE',sourceId:id,lines:{create:lines}}});await tx.cashTransaction.create({data:{organizationId:org,cashAccountId:cash.id,type:'EXPENSE',amount:e.amount,transactionDate:e.incurredAt,description:e.description||e.category,sourceType:'EXPENSE',sourceId:id}});return j});return entry}
 async ledger(org:string,from?:string,to?:string){const where:any={organizationId:org};if(from||to)where.entryDate={...(from?{gte:new Date(from)}:{}),...(to?{lte:new Date(to+'T23:59:59.999Z')}: {})};return this.prisma.journalEntry.findMany({where,include:{lines:{include:{account:true}}},orderBy:{entryDate:'asc'}})}
 async trialBalance(org:string,from?:string,to?:string){const rows=await this.ledger(org,from,to);const map=new Map<string,any>();for(const e of rows)for(const l of e.lines){const k=l.account.code;if(!map.has(k))map.set(k,{code:k,name:l.account.name,type:l.account.type,debit:0,credit:0});const x=map.get(k);x.debit+=Number(l.debit);x.credit+=Number(l.credit)}return [...map.values()].map(x=>({...x,debit:this.money(x.debit),credit:this.money(x.credit),balance:this.money(x.debit-x.credit)}))}
 async pnl(org:string,from?:string,to?:string){const tb=await this.trialBalance(org,from,to);const revenue=tb.filter(x=>x.type==='REVENUE').reduce((s,x)=>s+x.credit-x.debit,0);const expenses=tb.filter(x=>x.type==='EXPENSE').reduce((s,x)=>s+x.debit-x.credit,0);return {revenue:this.money(revenue),expenses:this.money(expenses),profit:this.money(revenue-expenses),period:{from,to}}}
 async vatReport(org:string,from?:string,to?:string){const rows=await this.prisma.journalLine.findMany({where:{journalEntry:{organizationId:org,...((from||to)?{entryDate:{...(from?{gte:new Date(from)}:{}),...(to?{lte:new Date(to+'T23:59:59.999Z')}: {})}}:{})}},include:{account:true}});const collected=rows.filter(x=>x.account.code==='445710').reduce((s,x)=>s+Number(x.credit)-Number(x.debit),0);const deductible=rows.filter(x=>x.account.code==='445660').reduce((s,x)=>s+Number(x.debit)-Number(x.credit),0);return {collected:this.money(collected),deductible:this.money(deductible),net:this.money(collected-deductible),position:collected-deductible>=0?'PAYABLE':'CREDIT',period:{from,to}}}
 async cashflowForecast(org:string,days=30){
  const horizon=Math.min(Math.max(Number(days)||30,7),180); const now=new Date(); const end=new Date(now); end.setDate(end.getDate()+horizon);
  const current=(await this.cashPosition(org)).total;
  const invoices=await this.prisma.invoice.findMany({where:{organizationId:org,status:{in:{SENT:'SENT',PARTIALLY_PAID:'PARTIALLY_PAID',OVERDUE:'OVERDUE'}},dueAt:{not:null,lte:end}},include:{payments:true}});
  const bills=await this.prisma.supplierBill.findMany({where:{organizationId:org,status:{in:['OPEN','PARTIALLY_PAID']},dueAt:{not:null,lte:end}},include:{payments:true}});
  const expenses=await this.prisma.expense.findMany({where:{organizationId:org,status:'APPROVED',incurredAt:{gte:now,lte:end}}});
  const buckets=Array.from({length:horizon+1},(_,i)=>{const d=new Date(now);d.setHours(0,0,0,0);d.setDate(d.getDate()+i);return {date:d.toISOString().slice(0,10),incoming:0,outgoing:0}});
  const idx=(d:Date)=>Math.min(horizon,Math.max(0,Math.floor((d.getTime()-now.getTime())/86400000)));
  for(const inv of invoices){const paid=inv.payments.reduce((a,p)=>a+Number(p.amount),0);const remaining=this.money(Number(inv.total)-paid);if(remaining>0){const d=inv.dueAt! < now ? now : inv.dueAt!;buckets[idx(d)].incoming+=remaining;}}
  for(const bill of bills){const paid=bill.payments.reduce((a,p)=>a+Number(p.amount),0);const remaining=this.money(Number(bill.total)-paid);if(remaining>0){const d=bill.dueAt! < now ? now : bill.dueAt!;buckets[idx(d)].outgoing+=remaining;}}
  for(const e of expenses)buckets[idx(e.incurredAt)].outgoing+=Number(e.amount);
  let projected=current;const daily=buckets.map(b=>{projected=this.money(projected+b.incoming-b.outgoing);return {...b,incoming:this.money(b.incoming),outgoing:this.money(b.outgoing),projectedBalance:projected}});
  return {currency:'MAD',horizonDays:horizon,currentBalance:current,expectedIncoming:this.money(daily.reduce((a,b)=>a+b.incoming,0)),expectedOutgoing:this.money(daily.reduce((a,b)=>a+b.outgoing,0)),projectedBalance:daily.at(-1)?.projectedBalance??current,daily};
 }

 async cashPosition(org:string){const accounts=await this.prisma.cashAccount.findMany({where:{organizationId:org,active:true}});const result=accounts.map(c=>({id:c.id,name:c.name,currency:c.currency,balance:this.money(Number(c.openingBalance)+0)}));for(const c of result){const rows=await this.prisma.cashTransaction.findMany({where:{cashAccountId:c.id,organizationId:org}});c.balance=this.money(c.balance+rows.reduce((s,r)=>s+(['INCOME','TRANSFER_IN'].includes(r.type)?Number(r.amount):-Number(r.amount),0)))}return {accounts:result,total:this.money(result.reduce((s,c)=>s+c.balance,0))}}
}
