import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import {PrismaService} from '../common/prisma.service';import {AuditService} from '../common/audit.service';
import {ImportBankLineDto,MatchBankLineDto} from './reconciliation.dto';
@Injectable()
export class ReconciliationService {constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
 private money(n:number){return Math.round((n+Number.EPSILON)*100)/100}
 async lines(org:string,cashAccountId:string,status?:string){return this.prisma.bankStatementLine.findMany({where:{organizationId:org,cashAccountId,...(status?{status}: {})},orderBy:{transactionDate:'desc'}})}
 async importLine(org:string,userId:string,d:ImportBankLineDto,request:any){const c=await this.prisma.cashAccount.findFirst({where:{id:d.cashAccountId,organizationId:org,active:true}});if(!c)throw new NotFoundException('Compte bancaire introuvable.');const row=await this.prisma.bankStatementLine.create({data:{organizationId:org,cashAccountId:c.id,externalId:d.externalId,transactionDate:new Date(d.transactionDate),description:d.description,reference:d.reference,amount:d.amount,direction:d.direction}});await this.audit.record({organizationId:org,userId,action:'IMPORT',entity:'BankStatementLine',entityId:row.id,next:row,ip:request.ip,userAgent:request.headers['user-agent']});return row}
 async suggestions(org:string,id:string){const line=await this.prisma.bankStatementLine.findFirst({where:{id,organizationId:org}});if(!line)throw new NotFoundException('Ligne bancaire introuvable.');const signed=line.direction==='CREDIT'?Number(line.amount):-Number(line.amount);return this.prisma.cashTransaction.findMany({where:{organizationId:org,cashAccountId:line.cashAccountId},orderBy:{transactionDate:'desc'},take:50}).then(rows=>rows.map(r=>{const rs=['INCOME','TRANSFER_IN'].includes(r.type)?Number(r.amount):-Number(r.amount);const day=Math.abs(new Date(r.transactionDate).getTime()-new Date(line.transactionDate).getTime())/86400000;const amountDiff=Math.abs(rs-signed);const score=(amountDiff<0.01?70:0)+(day<=2?20:day<=7?10:0)+((line.reference&&r.reference===line.reference)?10:0);return {...r,score}}).sort((a,b)=>b.score-a.score).slice(0,10))}
 async match(org:string,userId:string,id:string,d:MatchBankLineDto,request:any){const result=await this.prisma.$transaction(async tx=>{const line=await tx.bankStatementLine.findFirst({where:{id,organizationId:org}});if(!line)throw new NotFoundException('Ligne bancaire introuvable.');const txRow=await tx.cashTransaction.findFirst({where:{id:d.cashTransactionId,organizationId:org,cashAccountId:line.cashAccountId}});if(!txRow)throw new NotFoundException('Transaction de trésorerie introuvable.');const signed=['INCOME','TRANSFER_IN'].includes(txRow.type)?Number(txRow.amount):-Number(txRow.amount);const bankSigned=line.direction==='CREDIT'?Number(line.amount):-Number(line.amount);if(Math.abs(signed-bankSigned)>0.01)throw new BadRequestException('Le montant de la transaction ne correspond pas à la ligne bancaire.');return tx.bankStatementLine.update({where:{id:line.id},data:{status:'MATCHED',matchedCashTransactionId:txRow.id}})});await this.audit.record({organizationId:org,userId,action:'MATCH',entity:'BankStatementLine',entityId:result.id,next:result,ip:request.ip,userAgent:request.headers['user-agent']});return result}
 async unmatch(org:string,userId:string,id:string,request:any){const row=await this.prisma.bankStatementLine.findFirst({where:{id,organizationId:org}});if(!row)throw new NotFoundException('Ligne bancaire introuvable.');const out=await this.prisma.bankStatementLine.update({where:{id},data:{status:'UNMATCHED',matchedCashTransactionId:null}});await this.audit.record({organizationId:org,userId,action:'UNMATCH',entity:'BankStatementLine',entityId:id,next:out,ip:request.ip,userAgent:request.headers['user-agent']});return out}
 async summary(org:string,cashAccountId:string){const lines=await this.prisma.bankStatementLine.findMany({where:{organizationId:org,cashAccountId}});const matched=lines.filter(x=>x.status==='MATCHED');return {totalLines:lines.length,matched:matched.length,unmatched:lines.length-matched.length,bankBalance:this.money(lines.reduce((s,l)=>s+(l.direction==='CREDIT'?Number(l.amount):-Number(l.amount)),0))}}
}
