'use client';
import {useEffect,useMemo,useState} from 'react';
import {BarChart3,Plus,RefreshCw} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
const money=(n:number)=>new Intl.NumberFormat('fr-MA',{style:'currency',currency:'MAD',maximumFractionDigits:2}).format(n||0);
export default function ProjectsPage(){const [projects,setProjects]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [name,setName]=useState('');const [budget,setBudget]=useState('');
 async function load(){setLoading(true);setError('');try{const org=localStorage.getItem('sahlbiz_org');const r=await fetch(`${API}/projects`,{credentials:'include',headers:{'x-organization-id':org||''}});if(!r.ok)throw new Error('Impossible de charger les projets.');const data=await r.json();setProjects(Array.isArray(data)?data:data.items||[]);}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(){if(!name.trim())return;const org=localStorage.getItem('sahlbiz_org');const r=await fetch(`${API}/projects`,{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org||''},body:JSON.stringify({name,budget:budget?Number(budget):undefined})});if(r.ok){setName('');setBudget('');load()}else setError('Création impossible.')}
 const totals=useMemo(()=>projects.reduce((a,p)=>({revenue:a.revenue+(p.revenue||0),cost:a.cost+(p.actualCost||0),margin:a.margin+(p.margin||0)}),{revenue:0,cost:0,margin:0}),[projects]);
 return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Projets</h1><p className="text-sm text-gray-500">Suivi du budget, des tâches et de la rentabilité.</p></div><button onClick={load} className="p-2 border rounded-lg"><RefreshCw size={17}/></button></div><div className="grid md:grid-cols-3 gap-4"><K title="CA projets" value={money(totals.revenue)}/><K title="Coûts réels" value={money(totals.cost)}/><K title="Marge" value={money(totals.margin)}/></div><div className="bg-white border rounded-xl p-4"><div className="font-semibold mb-3">Nouveau projet</div><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom du projet" className="flex-1 border rounded-lg px-3 py-2"/><input value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Budget MAD" type="number" className="w-40 border rounded-lg px-3 py-2"/><button onClick={create} className="px-4 rounded-lg bg-[var(--primary)] text-white flex items-center gap-2"><Plus size={16}/>Créer</button></div></div>{error&&<div className="text-sm text-red-600">{error}</div>}<div className="bg-white border rounded-xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="text-left p-3">Projet</th><th className="text-right p-3">Budget</th><th className="text-right p-3">CA</th><th className="text-right p-3">Coûts</th><th className="text-right p-3">Marge</th><th className="text-right p-3">Avancement</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center text-gray-500">Chargement…</td></tr>:projects.map(p=><tr key={p.id} className="border-t"><td className="p-3 font-medium">{p.name}<div className="text-xs text-gray-400">{p.customer?.name||'Sans client'}</div></td><td className="p-3 text-right">{p.budget==null?'—':money(Number(p.budget))}</td><td className="p-3 text-right">{money(p.revenue||0)}</td><td className="p-3 text-right">{money(p.actualCost||0)}</td><td className={`p-3 text-right font-semibold ${(p.margin||0)<0?'text-red-600':'text-green-700'}`}>{money(p.margin||0)}</td><td className="p-3 text-right">{p.progress||0}%</td></tr>)}</tbody></table></div></div>}
function K({title,value}:{title:string,value:string}){return <div className="bg-white border rounded-xl p-4"><div className="text-xs text-gray-500">{title}</div><div className="text-xl font-bold mt-1">{value}</div></div>}
