import {Injectable} from '@nestjs/common';
import {PrismaService} from '../common/prisma.service';
const N=(v:any)=>Number(v??0); const D=(v?:string)=>v?new Date(v):new Date(new Date().getFullYear(),0,1); const E=(v?:string)=>v?new Date(v+'T23:59:59.999Z'):new Date();
@Injectable() export class AnalyticsService {constructor(private readonly db:PrismaService){}
 async executive(o:string,f?:string,t?:string){const from=D(f),to=E(t);const [i,p,e,s,q,st,pr]=await Promise.all([this.db.invoice.findMany({where:{organizationId:o,issuedAt:{gte:from,lte:to},status:{not:'CANCELLED'}},select:{total:true,status:true}}),this.db.payment.findMany({where:{organizationId:o,paidAt:{gte:from,lte:to}},select:{amount:true}}),this.db.expense.findMany({where:{organizationId:o,incurredAt:{gte:from,lte:to},status:{in:['APPROVED','PAID']}},select:{amount:true}}),this.db.supplierBill.findMany({where:{organizationId:o,issuedAt:{gte:from,lte:to}},select:{total:true}}),this.db.quote.findMany({where:{organizationId:o,createdAt:{gte:from,lte:to}},select:{status:true}}),this.db.warehouseStock.findMany({where:{warehouse:{organizationId:o}},select:{quantity:true,product:{select:{purchasePrice:true}}}}),this.db.project.count({where:{organizationId:o}})]);const revenue=i.reduce((a,x)=>a+N(x.total),0),payments=p.reduce((a,x)=>a+N(x.amount),0),expenses=e.reduce((a,x)=>a+N(x.amount),0),payables=s.reduce((a,x)=>a+N(x.total),0),stockValue=st.reduce((a,x)=>a+N(x.quantity)*N(x.product.purchasePrice),0),accepted=q.filter(x=>x.status==='ACCEPTED'||x.status==='CONVERTED').length;return{period:{from,to},currency:'MAD',kpis:{revenue,payments,expenses,profit:revenue-expenses,receivables:i.filter(x=>x.status!=='PAID').reduce((a,x)=>a+N(x.total),0),payables,stockValue,projectCount:pr,quoteConversionRate:q.length?accepted/q.length:0}}}
 async sales(o:string,f?:string,t?:string){
  const from=D(f),to=E(t);
  const i=await this.db.invoice.findMany({where:{organizationId:o,issuedAt:{gte:from,lte:to},status:{not:'CANCELLED'}},select:{total:true,customer:{select:{name:true}}}});
  const q=await this.db.quote.findMany({where:{organizationId:o,createdAt:{gte:from,lte:to}},select:{status:true,total:true}});
  const items=await this.db.invoiceItem.findMany({where:{invoice:{organizationId:o,issuedAt:{gte:from,lte:to},status:{not:'CANCELLED'}}},select:{description:true,lineTotal:true,product:{select:{name:true}}}});
  const c=new Map<string,number>(),p=new Map<string,number>();
  for(const x of i)c.set(x.customer.name,(c.get(x.customer.name)||0)+N(x.total));
  for(const x of items){const k=x.product?.name||x.description;p.set(k,(p.get(k)||0)+N(x.lineTotal));}
  return{period:{from,to},revenue:i.reduce((a,x)=>a+N(x.total),0),invoiceCount:i.length,quoteCount:q.length,acceptedQuotes:q.filter(x=>x.status==='ACCEPTED'||x.status==='CONVERTED').length,topCustomers:[...c].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value})),topProducts:[...p].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value}))};
 }
 async finance(o:string,f?:string,t?:string){const from=D(f),to=E(t);const lines=await this.db.journalLine.findMany({where:{journalEntry:{organizationId:o,entryDate:{gte:from,lte:to}}},select:{debit:true,credit:true,account:{select:{code:true,name:true,type:true}}}});let revenue=0,expenses=0;for(const x of lines){if(x.account.type==='REVENUE')revenue+=N(x.credit)-N(x.debit);if(x.account.type==='EXPENSE')expenses+=N(x.debit)-N(x.credit)}const cash=await this.db.cashAccount.findMany({where:{organizationId:o,active:true},select:{openingBalance:true,transactions:{where:{transactionDate:{lte:to}},select:{type:true,amount:true}}}});const cashBalance=cash.reduce((a,x)=>a+N(x.openingBalance)+x.transactions.reduce((b,z)=>b+(['INCOME','TRANSFER_IN'].includes(z.type)?N(z.amount):-N(z.amount)),0),0);const vat=lines.filter(x=>x.account.code==='445710'||x.account.code==='445660');const collected=vat.filter(x=>x.account.code==='445710').reduce((a,x)=>a+N(x.credit)-N(x.debit),0),deductible=vat.filter(x=>x.account.code==='445660').reduce((a,x)=>a+N(x.debit)-N(x.credit),0);return{period:{from,to},pnl:{revenue,expenses,profit:revenue-expenses},cashBalance,vat:{collected,deductible,net:collected-deductible}}}
 async operations(o:string,f?:string,t?:string){const [products,projects,openTasks,suppliers]=await Promise.all([this.db.product.findMany({where:{organizationId:o,active:true},select:{name:true,stock:true,minimumStock:true}}),this.db.project.findMany({where:{organizationId:o},select:{id:true,name:true,budget:true,invoices:{where:{status:{not:'CANCELLED'}},select:{total:true}},expenses:{where:{status:{in:['APPROVED','PAID']}},select:{amount:true}},tasks:{select:{status:true}}}}),this.db.task.count({where:{organizationId:o,status:{not:'DONE'}}}),this.db.supplier.count({where:{organizationId:o,active:true}})]);const lowStock=products.filter(x=>N(x.stock)<=N(x.minimumStock)).map(x=>({name:x.name,stock:N(x.stock),minimum:N(x.minimumStock)}));const projectMargins=projects.map(p=>{const revenue=p.invoices.reduce((a,x)=>a+N(x.total),0),cost=p.expenses.reduce((a,x)=>a+N(x.amount),0),done=p.tasks.filter(x=>x.status==='DONE').length;return{name:p.name,revenue,cost,margin:revenue-cost,marginRate:revenue?((revenue-cost)/revenue):0,taskCompletion:p.tasks.length?done/p.tasks.length:0,budget:N(p.budget)}});return{lowStock,openTasks,supplierCount:suppliers,projectMargins}}
}
