'use client';
import {apiFetch} from '../../../lib/api-client';
import {useEffect,useState} from 'react';

type Supplier={id:string;name:string;paymentTermsDays:number};
type Bill={id:string;number:string;externalNumber?:string;status:string;subtotal:number;tax:number;total:number;dueAt?:string;supplier:{name:string};payments:{amount:number}[]};
type Cash={id:string;name:string};

export default function PurchasesPage(){
 const [suppliers,setSuppliers]=useState<Supplier[]>([]),[bills,setBills]=useState<Bill[]>([]),[cash,setCash]=useState<Cash[]>([]);
 const [supplierId,setSupplierId]=useState(''),[subtotal,setSubtotal]=useState(''),[tax,setTax]=useState(''),[externalNumber,setExternalNumber]=useState('');
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const [s,b,c]=await Promise.all([apiFetch('/suppliers'),apiFetch('/suppliers/bills'),apiFetch('/finance/cash-accounts')]);if(s.ok)setSuppliers(await s.json());if(b.ok)setBills(await b.json());if(c.ok)setCash(await c.json());setLoading(false)}
 useEffect(()=>{load()},[]);
 async function createBill(e:React.FormEvent){e.preventDefault();if(!supplierId||!subtotal)return;setSaving(true);setError('');const r=await apiFetch('/suppliers/bills',{method:'POST',body:JSON.stringify({supplierId,subtotal:Number(subtotal),tax:Number(tax||0),externalNumber:externalNumber||undefined})});if(!r.ok)setError(await r.text()||'Création impossible.');else{setSubtotal('');setTax('');setExternalNumber('');await load()}setSaving(false)}
 async function post(id:string){const r=await apiFetch(`/suppliers/bills/${id}/post`,{method:'POST'});if(!r.ok)setError(await r.text()||'Comptabilisation impossible.');else await load()}
 async function pay(bill:Bill){const paid=bill.payments.reduce((s,p)=>s+Number(p.amount),0);const remaining=Number(bill.total)-paid;const account=cash[0];if(!account){setError('Aucun compte de trésorerie disponible.');return}const amount=window.prompt(`Montant à payer (reste ${remaining.toFixed(2)} MAD)`,remaining.toFixed(2));if(amount===null)return;const r=await apiFetch('/suppliers/payments',{method:'POST',body:JSON.stringify({supplierBillId:bill.id,cashAccountId:account.id,amount:Number(amount),paidAt:new Date().toISOString(),method:'BANK'})});if(!r.ok)setError(await r.text()||'Paiement impossible.');else await load()}
 return <section className="space-y-5"><div><h1 className="text-2xl font-bold">Achats fournisseurs</h1><p className="text-sm text-gray-500 mt-1">Factures fournisseurs, comptabilisation et règlements depuis les données tenant-scoped.</p></div>
 {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <form onSubmit={createBill} className="bg-white border rounded-xl p-5 grid md:grid-cols-5 gap-3 items-end"><label className="text-sm">Fournisseur<select required value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="mt-1 w-full border rounded-lg p-2"><option value="">Sélectionner</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm">HT<input required type="number" min="0" step="0.01" value={subtotal} onChange={e=>setSubtotal(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><label className="text-sm">TVA<input type="number" min="0" step="0.01" value={tax} onChange={e=>setTax(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><label className="text-sm">N° fournisseur<input value={externalNumber} onChange={e=>setExternalNumber(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><button disabled={saving} className="rounded-lg bg-[var(--primary)] text-white p-2.5 disabled:opacity-50">{saving?'Création…':'Créer la facture'}</button></form>
 <div className="bg-white border rounded-xl overflow-hidden">{loading?<div className="p-8 text-sm text-gray-500">Chargement…</div>:bills.length===0?<div className="p-10 text-center text-sm text-gray-500">Aucune facture fournisseur.</div>:<table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr><th className="p-3 text-left">Facture</th><th className="p-3 text-left">Fournisseur</th><th className="p-3 text-right">TTC</th><th className="p-3 text-right">Solde</th><th className="p-3 text-left">Statut</th><th className="p-3"/></tr></thead><tbody>{bills.map(b=>{const paid=b.payments.reduce((s,p)=>s+Number(p.amount),0);const balance=Number(b.total)-paid;return <tr key={b.id} className="border-t"><td className="p-3 font-medium">{b.number}{b.externalNumber&&<span className="text-xs text-gray-400 ml-2">{b.externalNumber}</span>}</td><td className="p-3">{b.supplier.name}</td><td className="p-3 text-right">{Number(b.total).toLocaleString('fr-MA')} MAD</td><td className="p-3 text-right">{balance.toLocaleString('fr-MA')} MAD</td><td className="p-3">{b.status}</td><td className="p-3 text-right space-x-2">{b.status==='OPEN'&&<button onClick={()=>post(b.id)} className="text-xs underline">Comptabiliser</button>}{balance>0&&b.status!=='OPEN'&&<button onClick={()=>pay(b)} className="text-xs underline">Payer</button>}</td></tr>})}</tbody></table>}</div></section>
}