'use client';
import {apiFetch,getOrganizationId,setOrganizationId} from '../../../lib/api-client';
import {useEffect,useState} from 'react';
type Pnl={revenue:number;expenses:number;profit:number}; type Cash={total:number;accounts:{id:string;name:string;balance:number}[]}; type Row={code:string;name:string;debit:number;credit:number;balance:number};
export default function FinancePage(){
 const [pnl,setPnl]=useState<Pnl|null>(null),[cash,setCash]=useState<Cash|null>(null),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);const org=getOrganizationId()||'',h={'x-organization-id':org};const [a,b,c]=await Promise.all([apiFetch(+'/finance/pnl',{credentials:'include',headers:h}),apiFetch(+'/finance/cash-position',{credentials:'include',headers:h}),apiFetch(+'/finance/trial-balance',{credentials:'include',headers:h})]);if(!a.ok||!b.ok||!c.ok){setError('Impossible de charger les données comptables.')}else{setPnl(await a.json());setCash(await b.json());setRows(await c.json())}setLoading(false)}
 useEffect(()=>{load();const onOrg=()=>load();window.addEventListener('sahlbiz-org-change',onOrg);return()=>window.removeEventListener('sahlbiz-org-change',onOrg)},[]);
 if(loading)return <div className="py-16 text-center text-gray-500">Chargement…</div>; if(error)return <div className="rounded-xl border bg-red-50 p-5 text-sm text-red-700">{error}</div>;
 return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Finance & comptabilité</h1><p className="text-sm text-gray-500">États calculés depuis les écritures de l’organisation active.</p></div><div className="grid md:grid-cols-3 gap-4">{[['Chiffre d’affaires',pnl?.revenue],['Dépenses',pnl?.expenses],['Résultat',pnl?.profit]].map(([l,v])=><div key={String(l)} className="bg-white border rounded-xl p-5"><div className="text-sm text-gray-500">{l}</div><div className="text-2xl font-bold mt-2">{Number(v||0).toLocaleString('fr-MA')} MAD</div></div>)}</div><div className="bg-white border rounded-xl p-5"><h2 className="font-semibold">Trésorerie</h2><div className="text-2xl font-bold mt-2">{Number(cash?.total||0).toLocaleString('fr-MA')} MAD</div><div className="mt-4 space-y-2">{cash?.accounts?.map(a=><div key={a.id} className="flex justify-between text-sm border-t pt-2"><span>{a.name}</span><span>{Number(a.balance).toLocaleString('fr-MA')} MAD</span></div>)}</div></div><div className="bg-white border rounded-xl overflow-hidden"><div className="p-4"><h2 className="font-semibold">Balance générale</h2></div>{rows.length?<table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Compte</th><th className="p-3 text-left">Intitulé</th><th className="p-3 text-right">Débit</th><th className="p-3 text-right">Crédit</th><th className="p-3 text-right">Solde</th></tr></thead><tbody>{rows.map(x=><tr key={x.code} className="border-t"><td className="p-3 font-mono">{x.code}</td><td className="p-3">{x.name}</td><td className="p-3 text-right">{Number(x.debit||0).toLocaleString('fr-MA')}</td><td className="p-3 text-right">{Number(x.credit||0).toLocaleString('fr-MA')}</td><td className="p-3 text-right">{Number(x.balance||0).toLocaleString('fr-MA')}</td></tr>)}</tbody></table>:<div className="p-8 text-center text-gray-500">Aucune écriture.</div>}</div></section>
}