import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import {Prisma,PrismaClient} from '@prisma/client';
import {PrismaService} from '../common/prisma.service';
import {AuditService} from '../common/audit.service';
import {CreateSupplierBillDto,CreateSupplierDto,CreateSupplierPaymentDto} from './suppliers.dto';
@Injectable()
export class SuppliersService {
 constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
 private money(n:number){return Math.round((n+Number.EPSILON)*100)/100}
 private async account(tx:PrismaClient|Prisma.TransactionClient,org:string,code:string){const a=await tx.account.findFirst({where:{organizationId:org,code,active:true}});if(!a)throw new BadRequestException(`Compte ${code} introuvable.`);return a}
 private async nextJournal(tx:PrismaClient|Prisma.TransactionClient,org:string){const year=new Date().getFullYear();const prefix=`JE-${year}-`;const last=await tx.journalEntry.findFirst({where:{organizationId:org,number:{startsWith:prefix}},orderBy:{number:'desc'}});const n=last?Number(last.number.slice(-4))+1:1;return `${prefix}${String(n).padStart(4,'0')}`}
 private async nextBill(tx:PrismaClient|Prisma.TransactionClient,org:string){const year=new Date().getFullYear();const prefix=`FF-${year}-`;const last=await tx.supplierBill.findFirst({where:{organizationId:org,number:{startsWith:prefix}},orderBy:{number:'desc'}});const n=last?Number(last.number.slice(-4))+1:1;return `${prefix}${String(n).padStart(4,'0')}`}
 async list(org:string){return this.prisma.supplier.findMany({where:{organizationId:org},orderBy:{name:'asc'}})}
 async create(org:string,userId:string,dto:CreateSupplierDto,request:any){const s=await this.prisma.supplier.create({data:{organizationId:org,...dto,name:dto.name.trim()}});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'Supplier',entityId:s.id,next:s,ip:request.ip,userAgent:request.headers['user-agent']});return s}
 async bills(org:string){return this.prisma.supplierBill.findMany({where:{organizationId:org},include:{supplier:true,payments:true},orderBy:{issuedAt:'desc'}})}
 async createBill(org:string,userId:string,dto:CreateSupplierBillDto,request:any){const total=this.money(dto.subtotal+dto.tax);const supplier=await this.prisma.supplier.findFirst({where:{id:dto.supplierId,organizationId:org,active:true}});if(!supplier)throw new NotFoundException('Fournisseur introuvable.');const bill=await this.prisma.$transaction(async tx=>{const number=await this.nextBill(tx,org);return tx.supplierBill.create({data:{organizationId:org,supplierId:supplier.id,number,externalNumber:dto.externalNumber?.trim(),subtotal:dto.subtotal,tax:dto.tax,total,issuedAt:dto.issuedAt?new Date(dto.issuedAt):new Date(),dueAt:dto.dueAt?new Date(dto.dueAt):new Date(Date.now()+supplier.paymentTermsDays*86400000),notes:dto.notes?.trim()}})});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'SupplierBill',entityId:bill.id,next:bill,ip:request.ip,userAgent:request.headers['user-agent']});return bill}
 async payments(org:string){return this.prisma.supplierPayment.findMany({where:{organizationId:org},include:{supplier:true,supplierBill:true,cashAccount:true},orderBy:{paidAt:'desc'}})}
 async pay(org:string,userId:string,dto:CreateSupplierPaymentDto,request:any){const result=await this.prisma.$transaction(async tx=>{const bill=await tx.supplierBill.findFirst({where:{id:dto.supplierBillId,organizationId:org},include:{payments:true}});if(!bill)throw new NotFoundException('Facture fournisseur introuvable.');const posted=await tx.journalEntry.findFirst({where:{organizationId:org,sourceType:'SUPPLIER_BILL',sourceId:bill.id}});if(!posted)throw new BadRequestException('Comptabilisez la facture fournisseur avant son paiement.');const cash=await tx.cashAccount.findFirst({where:{id:dto.cashAccountId,organizationId:org,active:true},include:{account:true}});if(!cash)throw new NotFoundException('Compte bancaire introuvable.');const paid=bill.payments.reduce((s,p)=>s+Number(p.amount),0);const remaining=this.money(Number(bill.total)-paid);if(dto.amount>remaining+0.001)throw new BadRequestException('Le paiement dépasse le solde fournisseur.');const payment=await tx.supplierPayment.create({data:{organizationId:org,supplierBillId:bill.id,supplierId:bill.supplierId,cashAccountId:cash.id,amount:dto.amount,paidAt:new Date(dto.paidAt),method:dto.method,reference:dto.reference}});const ap=await this.account(tx,org,'401000');const vat=await this.account(tx,org,'445660');const expense=await this.account(tx,org,'613000');const number=await this.nextJournal(tx,org);const journal=await tx.journalEntry.create({data:{organizationId:org,number,entryDate:new Date(dto.paidAt),description:`Paiement fournisseur ${bill.number}`,sourceType:'SUPPLIER_PAYMENT',sourceId:payment.id,lines:{create:[{accountId:ap.id,debit:dto.amount,credit:0},{accountId:cash.accountId,debit:0,credit:dto.amount}]}}});
 await tx.cashTransaction.create({data:{organizationId:org,cashAccountId:cash.id,type:'EXPENSE',amount:dto.amount,transactionDate:new Date(dto.paidAt),description:`Paiement ${bill.number}`,reference:dto.reference,sourceType:'SUPPLIER_PAYMENT',sourceId:payment.id}});const newPaid=paid+dto.amount;await tx.supplierBill.update({where:{id:bill.id},data:{status:newPaid>=Number(bill.total)-0.001?'PAID':'PARTIALLY_PAID'}});return {payment,journal,expenseAccount:expense.code,vatAccount:vat.code}});await this.audit.record({organizationId:org,userId,action:'PAY',entity:'SupplierPayment',entityId:result.payment.id,next:result.payment,ip:request.ip,userAgent:request.headers['user-agent']});return result}
 async postBill(org:string,userId:string,id:string,request:any){return this.prisma.$transaction(async tx=>{const bill=await tx.supplierBill.findFirst({where:{id,organizationId:org}});if(!bill)throw new NotFoundException('Facture fournisseur introuvable.');const existing=await tx.journalEntry.findFirst({where:{organizationId:org,sourceType:'SUPPLIER_BILL',sourceId:id}});if(existing)return existing;const ap=await this.account(tx,org,'401000');const expense=await this.account(tx,org,'613000');const vat=await this.account(tx,org,'445660');const number=await this.nextJournal(tx,org);const entry=await tx.journalEntry.create({data:{organizationId:org,number,entryDate:bill.issuedAt||new Date(),description:`Facture fournisseur ${bill.number}`,sourceType:'SUPPLIER_BILL',sourceId:id,lines:{create:[{accountId:expense.id,debit:Number(bill.subtotal),credit:0},{accountId:vat.id,debit:Number(bill.tax),credit:0},{accountId:ap.id,debit:0,credit:Number(bill.total)}]}}});await this.audit.record({organizationId:org,userId,action:'POST',entity:'JournalEntry',entityId:entry.id,next:entry,ip:request.ip,userAgent:request.headers['user-agent']});return entry})}
 async balances(org:string){const bills=await this.prisma.supplierBill.findMany({where:{organizationId:org},include:{supplier:true,payments:true}});return bills.map(b=>{const paid=b.payments.reduce((s,p)=>s+Number(p.amount),0);return {supplierId:b.supplierId,supplier:b.supplier.name,billId:b.id,number:b.number,total:Number(b.total),paid:this.money(paid),balance:this.money(Number(b.total)-paid),dueAt:b.dueAt,status:b.status}}).filter(x=>x.balance>0)}
}
