import {BadRequestException,ForbiddenException,Injectable,NotFoundException} from '@nestjs/common';
import {PrismaService} from '../common/prisma.service';
import {AuditService} from '../common/audit.service';
import {CreateExpenseDto,PayExpenseDto} from './expenses.dto';
@Injectable()
export class ExpensesService {
 constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
 private money(n:number){return Math.round((n+Number.EPSILON)*100)/100}
 private async assertRef(org:string,dto:CreateExpenseDto){
  if(dto.supplierId && !await this.prisma.supplier.findFirst({where:{id:dto.supplierId,organizationId:org,active:true}})) throw new BadRequestException('Fournisseur introuvable.');
  if(dto.employeeId && !await this.prisma.user.findFirst({where:{id:dto.employeeId,memberships:{some:{organizationId:org}}}})) throw new BadRequestException('Employé introuvable.');
  if(dto.projectId && !await this.prisma.project.findFirst({where:{id:dto.projectId,organizationId:org}})) throw new BadRequestException('Projet introuvable.');
 }
 async list(org:string,status?:string){return this.prisma.expense.findMany({where:{organizationId:org,...(status?{status:status as any}:{})},include:{supplier:true,project:true,employee:{select:{id:true,name:true,email:true}},cashAccount:true},orderBy:{incurredAt:'desc'}})}
 async create(org:string,userId:string,dto:CreateExpenseDto,request:any){await this.assertRef(org,dto);const taxRate=dto.taxRate??0;const amount=this.money(dto.amount);const tax=this.money(amount*taxRate/(100+taxRate));const net=this.money(amount-tax);const e=await this.prisma.expense.create({data:{organizationId:org,category:dto.category,amount,netAmount:net,taxRate,taxAmount:tax,incurredAt:new Date(dto.incurredAt),description:dto.description,accountCode:dto.accountCode,supplierId:dto.supplierId,employeeId:dto.employeeId,projectId:dto.projectId,attachmentUrl:dto.attachmentUrl,paymentMethod:dto.paymentMethod}});await this.audit.record({organizationId:org,userId,action:'CREATE',entity:'Expense',entityId:e.id,next:e,ip:request.ip,userAgent:request.headers['user-agent']});return e}
 async approve(org:string,userId:string,id:string,request:any){const e=await this.prisma.expense.findFirst({where:{id,organizationId:org}});if(!e)throw new NotFoundException('Dépense introuvable.');if(e.status!=='SUBMITTED')throw new BadRequestException('Seules les dépenses soumises peuvent être approuvées.');const r=await this.prisma.expense.update({where:{id},data:{status:'APPROVED',approvedAt:new Date(),approvedById:userId}});await this.audit.record({organizationId:org,userId,action:'APPROVE',entity:'Expense',entityId:id,previous:e,next:r,ip:request.ip,userAgent:request.headers['user-agent']});return r}
 async reject(org:string,userId:string,id:string,request:any){const e=await this.prisma.expense.findFirst({where:{id,organizationId:org}});if(!e)throw new NotFoundException('Dépense introuvable.');if(e.status!=='SUBMITTED')throw new BadRequestException('Seules les dépenses soumises peuvent être rejetées.');const r=await this.prisma.expense.update({where:{id},data:{status:'REJECTED'}});await this.audit.record({organizationId:org,userId,action:'REJECT',entity:'Expense',entityId:id,previous:e,next:r,ip:request.ip,userAgent:request.headers['user-agent']});return r}
 async pay(org:string,userId:string,id:string,dto:PayExpenseDto,request:any){const e=await this.prisma.expense.findFirst({where:{id,organizationId:org}});if(!e)throw new NotFoundException('Dépense introuvable.');if(e.status!=='APPROVED')throw new BadRequestException('La dépense doit être approuvée avant paiement.');const cash=await this.prisma.cashAccount.findFirst({where:{id:dto.cashAccountId,organizationId:org,active:true},include:{account:true}});if(!cash)throw new BadRequestException('Compte de trésorerie introuvable.');const existing=await this.prisma.journalEntry.findFirst({where:{organizationId:org,sourceType:'EXPENSE',sourceId:id}});if(existing) return e;
 const number=`JE-${new Date(dto.paidAt||new Date()).getFullYear()}-${Date.now()}`;
 const result=await this.prisma.$transaction(async tx=>{const expenseAccount=await tx.account.findFirst({where:{organizationId:org,code:e.accountCode||'613000'}});if(!expenseAccount)throw new BadRequestException('Compte de charge introuvable.');const lines:any[]=[{accountId:expenseAccount.id,debit:Number(e.netAmount||e.amount),credit:0,description:`Dépense ${e.category}`}];if(Number(e.taxAmount)>0){const vat=await tx.account.findFirst({where:{organizationId:org,code:'445660'}});if(!vat)throw new BadRequestException('Compte TVA déductible introuvable.');lines.push({accountId:vat.id,debit:Number(e.taxAmount),credit:0,description:'TVA déductible'});}lines.push({accountId:cash.accountId,debit:0,credit:Number(e.amount)});const j=await tx.journalEntry.create({data:{organizationId:org,number,entryDate:new Date(dto.paidAt||new Date()),description:e.description||`Dépense ${e.category}`,sourceType:'EXPENSE',sourceId:id,lines:{create:lines}}});await tx.cashTransaction.create({data:{organizationId:org,cashAccountId:cash.id,type:'EXPENSE',amount:e.amount,transactionDate:new Date(dto.paidAt||new Date()),description:e.description||e.category,reference:dto.reference,sourceType:'EXPENSE',sourceId:id}});return tx.expense.update({where:{id},data:{status:'PAID',cashAccountId:cash.id,paidAt:new Date(dto.paidAt||new Date())}})});
 await this.audit.record({organizationId:org,userId,action:'PAY',entity:'Expense',entityId:id,next:result,ip:request.ip,userAgent:request.headers['user-agent']});return result}
}
