'use client';
import {FormEvent,useEffect,useState} from 'react';
import {FileText,Upload,Download,Trash2,Search,Clock3,RefreshCw} from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
type Doc={id:string;name:string;category:string;mimeType:string;sizeBytes:number;currentVersion:number;expiresAt?:string;tags?:{id:string;name:string}[];createdAt:string};
const labels: Record<string, string> = {CONTRACT:'Contrat',INVOICE:'Facture',QUOTE:'Devis',RECEIPT:'Reçu',COMPANY:'Entreprise',CUSTOMER:'Client',PROJECT:'Projet',OTHER:'Autre'};
export default function DocumentsPage(){const [org,setOrg]=useState(''),[orgs,setOrgs]=useState<any[]>([]),[rows,setRows]=useState<Doc[]>([]),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[file,setFile]=useState<File|null>(null),[cat,setCat]=useState('OTHER'),[entityType,setEntityType]=useState(''),[entityId,setEntityId]=useState(''),[expiresAt,setExpiresAt]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 function orgId(){return org||localStorage.getItem('sahlbiz_org')||''}
 async function init(){const r=await fetch(`${API}/auth/me`,{credentials:'include'});if(r.ok){const d=await r.json();const saved=localStorage.getItem('sahlbiz_org');setOrgs(d.organizations||[]);setOrg(d.organizations?.some((x:any)=>x.organizationId===saved)?saved:d.organizations?.[0]?.organizationId||'')}}
 async function load(){const o=orgId();if(!o)return;setLoading(true);const qs=new URLSearchParams();if(search)qs.set('search',search);if(category)qs.set('category',category);const r=await fetch(`${API}/documents?${qs}`,{credentials:'include',headers:{'x-organization-id':o}});setRows(r.ok?(await r.json()).items:[]);setLoading(false)}
 useEffect(()=>{init()},[]);useEffect(()=>{if(org){localStorage.setItem('sahlbiz_org',org);load()}},[org]);useEffect(()=>{const t=setTimeout(()=>load(),250);return()=>clearTimeout(t)},[search,category]);
 async function upload(e:FormEvent){e.preventDefault();if(!file)return;setError('');const fd=new FormData();fd.append('file',file);fd.append('category',cat);if(entityType)fd.append('entityType',entityType);if(entityId)fd.append('entityId',entityId);if(expiresAt)fd.append('expiresAt',new Date(expiresAt).toISOString());const r=await fetch(`${API}/documents`,{method:'POST',credentials:'include',headers:{'x-organization-id':orgId()},body:fd});if(!r.ok){setError('Échec de l’envoi du document.');return}setFile(null);(document.getElementById('document-file') as HTMLInputElement).value='';load()}
 async function download(id:string,name:string){const r=await fetch(`${API}/documents/${id}/download`,{credentials:'include',headers:{'x-organization-id':orgId()}});if(!r.ok)return;const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
 async function version(id:string,f:File){const fd=new FormData();fd.append('file',f);const r=await fetch(`${API}/documents/${id}/versions`,{method:'POST',credentials:'include',headers:{'x-organization-id':orgId()},body:fd});if(!r.ok)setError('Impossible de créer une nouvelle version.');else load()} async function remove(id:string){if(!confirm('Supprimer ce document et toutes ses versions ?'))return;await fetch(`${API}/documents/${id}`,{method:'DELETE',credentials:'include',headers:{'x-organization-id':orgId()}});load()}
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-gray-500">Gestion documentaire</p><h1 className="text-2xl font-bold">Documents</h1><p className="text-sm text-gray-500 mt-1">Contrats, factures, reçus et fichiers clients dans un stockage objet sécurisé.</p></div><select value={org} onChange={e=>setOrg(e.target.value)} className="border rounded-lg px-3 py-2 h-fit">{orgs.map((o:any)=><option key={o.organizationId} value={o.organizationId}>{o.organization.name} · {o.role}</option>)}</select></div>{error&&<div className="bg-red-50 text-red-700 border border-red-100 rounded-lg p-3 text-sm">{error}</div>}
 <form onSubmit={upload} className="bg-white border rounded-xl p-5"><div className="flex items-center gap-2 font-semibold"><Upload size={17}/>Ajouter un document</div><div className="grid md:grid-cols-5 gap-3 mt-4"><input id="document-file" type="file" required onChange={e=>setFile(e.target.files?.[0]||null)} className="border rounded-lg p-2.5 md:col-span-2"/><select value={cat} onChange={e=>setCat(e.target.value)} className="border rounded-lg p-2.5">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input value={entityType} onChange={e=>setEntityType(e.target.value)} placeholder="Type lié (ex. project)" className="border rounded-lg p-2.5"/><input value={entityId} onChange={e=>setEntityId(e.target.value)} placeholder="ID lié" className="border rounded-lg p-2.5"/><input type="date" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)} className="border rounded-lg p-2.5"/><button className="bg-[var(--primary)] text-white rounded-lg px-4 py-2 inline-flex items-center justify-center gap-2"><Upload size={16}/>Envoyer</button></div><p className="text-xs text-gray-500 mt-3">Taille maximale : 20 Mo. Les fichiers sont conservés dans un stockage objet, pas dans PostgreSQL.</p></form>
 <div className="bg-white border rounded-xl overflow-hidden"><div className="p-4 border-b flex flex-wrap gap-3"><div className="flex items-center gap-2 flex-1 min-w-48"><Search size={17} className="text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un document…" className="outline-none flex-1 text-sm"/></div><select value={category} onChange={e=>setCategory(e.target.value)} className="border rounded-lg px-3 py-2 text-sm"><option value="">Toutes les catégories</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={load} className="border rounded-lg px-3 py-2"><RefreshCw size={16}/></button></div>{loading?<div className="p-8 text-gray-500">Chargement…</div>:!rows.length?<div className="p-10 text-center text-gray-500"><FileText className="mx-auto text-gray-300"/><p className="mt-3 font-medium">Aucun document</p></div>:<table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr><th className="text-left p-3">Document</th><th className="text-left p-3">Catégorie</th><th className="text-left p-3">Version</th><th className="text-left p-3">Expiration</th><th className="text-right p-3">Actions</th></tr></thead><tbody>{rows.map(d=><tr key={d.id} className="border-b last:border-0"><td className="p-3"><div className="font-medium">{d.name}</div><div className="text-xs text-gray-500">{(d.sizeBytes/1024/1024).toFixed(2)} Mo · {d.mimeType}</div>{d.tags?.length?<div className="text-xs text-gray-400 mt-1">{d.tags.map(t=>`#${t.name}`).join(' ')}</div>:null}</td><td className="p-3">{labels[d.category]||d.category}</td><td className="p-3">v{d.currentVersion}</td><td className="p-3">{d.expiresAt?<span className="inline-flex items-center gap-1"><Clock3 size={13}/>{new Date(d.expiresAt).toLocaleDateString('fr-FR')}</span>:'—'}</td><td className="p-3 text-right"><div className="inline-flex gap-2"><button onClick={()=>download(d.id,d.name)} className="border rounded-lg px-2 py-1.5 inline-flex gap-1 items-center"><Download size={14}/>Télécharger</button><label className="border rounded-lg px-2 py-1.5 cursor-pointer" title="Nouvelle version"><RefreshCw size={14}/><input type="file" className="hidden" onChange={e=>e.target.files?.[0]&&version(d.id,e.target.files[0])}/></label><button onClick={()=>remove(d.id)} className="border rounded-lg px-2 py-1.5 text-red-600"><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>}</div></div>}
