CREATE TYPE "AccountType" AS ENUM ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE');
CREATE TYPE "JournalSourceType" AS ENUM ('SALES_INVOICE','SALES_PAYMENT','EXPENSE','MANUAL');
CREATE TYPE "CashAccountType" AS ENUM ('BANK','CASH','MOBILE_WALLET');
CREATE TYPE "CashTransactionType" AS ENUM ('INCOME','EXPENSE','TRANSFER_IN','TRANSFER_OUT');
ALTER TABLE "Expense" ADD COLUMN "accountCode" TEXT, ADD COLUMN "cashAccountId" TEXT;
CREATE TABLE "Account" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"type" "AccountType" NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"parentId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JournalEntry" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"number" TEXT NOT NULL,"entryDate" TIMESTAMP(3) NOT NULL,"description" TEXT NOT NULL,"sourceType" "JournalSourceType" NOT NULL,"sourceId" TEXT,"postedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "JournalEntry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JournalLine" ("id" TEXT NOT NULL,"journalEntryId" TEXT NOT NULL,"accountId" TEXT NOT NULL,"debit" DECIMAL(14,2) NOT NULL DEFAULT 0,"credit" DECIMAL(14,2) NOT NULL DEFAULT 0,"description" TEXT,CONSTRAINT "JournalLine_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CashAccount" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"accountId" TEXT NOT NULL,"name" TEXT NOT NULL,"type" "CashAccountType" NOT NULL,"currency" TEXT NOT NULL DEFAULT 'MAD',"openingBalance" DECIMAL(14,2) NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CashAccount_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CashTransaction" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"cashAccountId" TEXT NOT NULL,"type" "CashTransactionType" NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"transactionDate" TIMESTAMP(3) NOT NULL,"description" TEXT,"reference" TEXT,"sourceType" TEXT,"sourceId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CashTransaction_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Account_organizationId_code_key" ON "Account"("organizationId","code");
CREATE INDEX "Account_organizationId_type_active_idx" ON "Account"("organizationId","type","active");
CREATE UNIQUE INDEX "JournalEntry_organizationId_number_key" ON "JournalEntry"("organizationId","number");
CREATE UNIQUE INDEX "JournalEntry_organizationId_sourceType_sourceId_key" ON "JournalEntry"("organizationId","sourceType","sourceId");
CREATE INDEX "JournalEntry_organizationId_entryDate_idx" ON "JournalEntry"("organizationId","entryDate");
CREATE INDEX "JournalLine_journalEntryId_idx" ON "JournalLine"("journalEntryId");
CREATE INDEX "JournalLine_accountId_idx" ON "JournalLine"("accountId");
CREATE UNIQUE INDEX "CashAccount_organizationId_name_key" ON "CashAccount"("organizationId","name");
CREATE INDEX "CashAccount_organizationId_active_idx" ON "CashAccount"("organizationId","active");
CREATE INDEX "CashTransaction_organizationId_transactionDate_idx" ON "CashTransaction"("organizationId","transactionDate");
CREATE INDEX "CashTransaction_cashAccountId_transactionDate_idx" ON "CashTransaction"("cashAccountId","transactionDate");
CREATE UNIQUE INDEX "CashTransaction_organizationId_sourceType_sourceId_key" ON "CashTransaction"("organizationId","sourceType","sourceId");
ALTER TABLE "Account" ADD CONSTRAINT "Account_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "JournalEntry" ADD CONSTRAINT "JournalEntry_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JournalLine" ADD CONSTRAINT "JournalLine_journalEntryId_fkey" FOREIGN KEY ("journalEntryId") REFERENCES "JournalEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JournalLine" ADD CONSTRAINT "JournalLine_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON UPDATE CASCADE;
ALTER TABLE "CashAccount" ADD CONSTRAINT "CashAccount_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CashAccount" ADD CONSTRAINT "CashAccount_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON UPDATE CASCADE;
ALTER TABLE "CashTransaction" ADD CONSTRAINT "CashTransaction_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CashTransaction" ADD CONSTRAINT "CashTransaction_cashAccountId_fkey" FOREIGN KEY ("cashAccountId") REFERENCES "CashAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_cashAccountId_fkey" FOREIGN KEY ("cashAccountId") REFERENCES "CashAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
