'use client';
import {useEffect,useMemo,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
type Customer={id:string;name:string}; type Product={id:string;name:string;sellingPrice:number|string;taxRate:number|string};
export default function PosPage(){
 const [customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[customerId,setCustomerId]=useState(''),[productId,setProductId]=useState(''),[qty,setQty]=useState(1),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{const org=localStorage.getItem('sahlbiz_org')||'',h={'x-organization-id':org};Promise.all([fetch(API+'/customers',{credentials:'include',headers:h}),fetch(API+'/products',{credentials:'include',headers:h})]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error();const c=await a.json(),p=await b.json();setCustomers(Array.isArray(c)?c:c.items||[]);setProducts(Array.isArray(p)?p:p.items||[])}).catch(()=>setMessage('Impossible de charger les clients ou produits.')).finally(()=>setLoading(false))},[]);
 const product=products.find(p=>p.id===productId);const total=useMemo(()=>{if(!product)return 0;const ht=Number(product.sellingPrice)*qty;return ht+ht*Number(product.taxRate||20)/100},[product,qty]);
 async function checkout(){if(!customerId||!product)return;const org=localStorage.getItem('sahlbiz_org')||'';const h={'content-type':'application/json','x-organization-id':org};const inv=await fetch(API+'/invoices',{method:'POST',credentials:'include',headers:h,body:JSON.stringify({customerId,items:[{productId:product.id,description:product.name,quantity:qty,unitPrice:Number(product.sellingPrice),taxRate:Number(product.taxRate||20)}]})});if(!inv.ok){setMessage('Création de la vente impossible.');return}const invoice=await inv.json();const pay=await fetch(API+'/payments',{method:'POST',credentials:'include',headers:h,body:JSON.stringify({invoiceId:invoice.id,amount:Number(invoice.total),method:'CASH'})});setMessage(pay.ok?'Vente enregistrée et paiement enregistré.':'Facture créée; paiement à finaliser.');}
 if(loading)return <div className="py-16 text-center text-gray-500">Chargement…</div>;
 return <section className="max-w-3xl space-y-6"><div><h1 className="text-2xl font-bold">Point de vente</h1><p className="text-sm text-gray-500">Vente réelle via l’API facturation et paiement.</p></div><div className="bg-white border rounded-xl p-5 space-y-4"><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="w-full border rounded-lg px-3 py-2"><option value="">Choisir un client</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={productId} onChange={e=>setProductId(e.target.value)} className="w-full border rounded-lg px-3 py-2"><option value="">Choisir un produit/service</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {Number(p.sellingPrice).toLocaleString('fr-MA')} MAD</option>)}</select><input min={1} type="number" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))} className="w-full border rounded-lg px-3 py-2"/><div className="flex justify-between border-t pt-4"><span>Total TTC</span><b>{total.toLocaleString('fr-MA')} MAD</b></div><button disabled={!customerId||!product} onClick={checkout} className="w-full rounded-lg bg-[var(--primary)] text-white px-4 py-3 disabled:opacity-50">Encaisser</button>{message&&<div className="text-sm text-gray-600">{message}</div>}</div></section>
