'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
export default function TasksPage(){const [tasks,setTasks]=useState<any[]>([]);const [title,setTitle]=useState('');const [status,setStatus]=useState('TODO');const [error,setError]=useState('');
 async function load(){const org=localStorage.getItem('sahlbiz_org');const r=await fetch(`${API}/tasks`,{credentials:'include',headers:{'x-organization-id':org||''}});if(r.ok)setTasks(await r.json());else setError('Impossible de charger les tâches.')}
 useEffect(()=>{load()},[]);
 async function add(){if(!title.trim())return;const org=localStorage.getItem('sahlbiz_org');const r=await fetch(`${API}/tasks`,{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org||''},body:JSON.stringify({title,status})});if(r.ok){setTitle('');load()}else setError('Création impossible.')}
 async function update(id:string,next:string){const org=localStorage.getItem('sahlbiz_org');await fetch(`${API}/tasks/${id}`,{method:'PATCH',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org||''},body:JSON.stringify({status:next})});load()}
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Tâches</h1><p className="text-sm text-gray-500">Suivez les actions de vos projets.</p></div><div className="bg-white border rounded-xl p-4 flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nouvelle tâche" className="flex-1 border rounded-lg px-3 py-2"/><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-lg px-3"><option>TODO</option><option>IN_PROGRESS</option><option>DONE</option><option>BLOCKED</option></select><button onClick={add} className="px-4 rounded-lg bg-[var(--primary)] text-white">Ajouter</button></div>{error&&<div className="text-red-600 text-sm">{error}</div>}<div className="grid md:grid-cols-4 gap-4">{['TODO','IN_PROGRESS','BLOCKED','DONE'].map(s=><section key={s} className="bg-gray-50 rounded-xl p-3 min-h-48"><h2 className="font-semibold text-sm mb-3">{s}</h2>{tasks.filter(t=>t.status===s).map(t=><div key={t.id} className="bg-white border rounded-lg p-3 mb-2"><div className="font-medium">{t.title}</div><div className="text-xs text-gray-400 mt-1">{t.project?.name||'Sans projet'}</div><select value={t.status} onChange={e=>update(t.id,e.target.value)} className="mt-2 text-xs border rounded px-2 py-1"><option>TODO</option><option>IN_PROGRESS</option><option>DONE</option><option>BLOCKED</option></select></div>)}</section>)}</div></div>}
