'use client';
import {apiFetch} from '../../../lib/api-client';
import {useEffect,useState} from 'react';
type Row={id:string;title:string;stage:string;value:number;probability:number;expectedClose?:string;customer?:{name:string}};
export default function OpportunitiesPage(){
 const [rows,setRows]=useState<Row[]>([]),[customers,setCustomers]=useState<{id:string;name:string}[]>([]),[title,setTitle]=useState(''),[customerId,setCustomerId]=useState(''),[stage,setStage]=useState('LEAD'),[value,setValue]=useState(''),[probability,setProbability]=useState(''),[error,setError]=useState('');
 async function load(){const [a,b]=await Promise.all([apiFetch('/opportunities'),apiFetch('/customers?pageSize=100')]);if(a.ok)setRows(await a.json());if(b.ok){const d=await b.json();setCustomers(d.data||[])}}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setError('');const r=await apiFetch('/opportunities',{method:'POST',body:JSON.stringify({title,customerId:customerId||undefined,stage,value:Number(value||0),probability:Number(probability||0)})});if(!r.ok){setError(await r.text()||'Création impossible.');return}setTitle('');setValue('');setProbability('');await load()}
 return <section className="space-y-5"><div><h1 className="text-2xl font-bold">Opportunités</h1><p className="text-sm text-gray-500">Pipeline commercial tenant-scoped.</p></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<form onSubmit={create} className="bg-white border rounded-xl p-5 grid md:grid-cols-5 gap-3 items-end"><label className="text-sm">Opportunité<input required value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><label className="text-sm">Client<select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="mt-1 w-full border rounded-lg p-2"><option value="">Aucun</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm">Étape<select value={stage} onChange={e=>setStage(e.target.value)} className="mt-1 w-full border rounded-lg p-2"><option>LEAD</option><option>QUALIFIED</option><option>PROPOSAL</option><option>NEGOTIATION</option><option>WON</option><option>LOST</option></select></label><label className="text-sm">Valeur<input type="number" min="0" step="0.01" value={value} onChange={e=>setValue(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><label className="text-sm">Probabilité %<input type="number" min="0" max="100" value={probability} onChange={e=>setProbability(e.target.value)} className="mt-1 w-full border rounded-lg p-2"/></label><button className="md:col-start-5 rounded-lg bg-[var(--primary)] text-white p-2.5">Ajouter</button></form><div className="bg-white border rounded-xl overflow-hidden">{rows.length===0?<div className="p-10 text-center text-sm text-gray-500">Aucune opportunité.</div>:<table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr><th className="p-3 text-left">Opportunité</th><th className="p-3 text-left">Client</th><th className="p-3 text-left">Étape</th><th className="p-3 text-right">Valeur</th><th className="p-3 text-right">Probabilité</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-medium">{x.title}</td><td className="p-3">{x.customer?.name||'—'}</td><td className="p-3">{x.stage}</td><td className="p-3 text-right">{Number(x.value).toLocaleString('fr-MA')} MAD</td><td className="p-3 text-right">{x.probability}%</td></tr>)}</tbody></table>}</div></section>
}