CREATE TYPE "DocumentCategory" AS ENUM ('CONTRACT','INVOICE','QUOTE','RECEIPT','COMPANY','CUSTOMER','PROJECT','OTHER');
CREATE TYPE "DocumentVisibility" AS ENUM ('ORGANIZATION','RESTRICTED');
CREATE TABLE "Document" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"category" "DocumentCategory" NOT NULL,"visibility" "DocumentVisibility" NOT NULL DEFAULT 'ORGANIZATION',"mimeType" TEXT NOT NULL,"sizeBytes" BIGINT NOT NULL,"storageKey" TEXT NOT NULL,"checksum" TEXT,"entityType" TEXT,"entityId" TEXT,"expiresAt" TIMESTAMP(3),"currentVersion" INTEGER NOT NULL DEFAULT 1,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Document_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentVersion" ("id" TEXT NOT NULL,"documentId" TEXT NOT NULL,"version" INTEGER NOT NULL,"storageKey" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"sizeBytes" BIGINT NOT NULL,"checksum" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DocumentVersion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentTag" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,CONSTRAINT "DocumentTag_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentPermission" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"documentId" TEXT NOT NULL,"userId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DocumentPermission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "_DocumentToDocumentTag" ("A" TEXT NOT NULL,"B" TEXT NOT NULL);
CREATE UNIQUE INDEX "DocumentVersion_documentId_version_key" ON "DocumentVersion"("documentId","version");
CREATE UNIQUE INDEX "DocumentTag_organizationId_name_key" ON "DocumentTag"("organizationId","name");
CREATE UNIQUE INDEX "DocumentPermission_documentId_userId_key" ON "DocumentPermission"("documentId","userId");
CREATE INDEX "Document_organizationId_category_createdAt_idx" ON "Document"("organizationId","category","createdAt");
CREATE INDEX "Document_organizationId_entityType_entityId_idx" ON "Document"("organizationId","entityType","entityId");
CREATE INDEX "Document_organizationId_expiresAt_idx" ON "Document"("organizationId","expiresAt");
CREATE INDEX "Document_organizationId_name_idx" ON "Document"("organizationId","name");
CREATE INDEX "DocumentVersion_documentId_createdAt_idx" ON "DocumentVersion"("documentId","createdAt");
CREATE INDEX "DocumentPermission_organizationId_userId_idx" ON "DocumentPermission"("organizationId","userId");
ALTER TABLE "Document" ADD CONSTRAINT "Document_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DocumentVersion" ADD CONSTRAINT "DocumentVersion_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentVersion" ADD CONSTRAINT "DocumentVersion_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DocumentTag" ADD CONSTRAINT "DocumentTag_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentPermission" ADD CONSTRAINT "DocumentPermission_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentPermission" ADD CONSTRAINT "DocumentPermission_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentPermission" ADD CONSTRAINT "DocumentPermission_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_DocumentToDocumentTag" ADD CONSTRAINT "_DocumentToDocumentTag_A_fkey" FOREIGN KEY ("A") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_DocumentToDocumentTag" ADD CONSTRAINT "_DocumentToDocumentTag_B_fkey" FOREIGN KEY ("B") REFERENCES "DocumentTag"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE UNIQUE INDEX "_DocumentToDocumentTag_AB_unique" ON "_DocumentToDocumentTag"("A","B");
CREATE INDEX "_DocumentToDocumentTag_B_index" ON "_DocumentToDocumentTag"("B");
