import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import {PrismaService} from '../common/prisma.service'; import {AuditService} from '../common/audit.service'; import {CreateCategoryDto,CreateProductDto,UpdateProductDto} from './products.dto';
import {InventoryService} from '../inventory/inventory.service';
@Injectable() export class ProductsService { constructor(private readonly prisma:PrismaService,private readonly audit:AuditService,private readonly inventory:InventoryService){}
 async categories(organizationId:string){return this.prisma.productCategory.findMany({where:{organizationId},orderBy:{name:'asc'}})}
 async createCategory(organizationId:string,userId:string,dto:CreateCategoryDto,request:any){const name=dto.name.trim();if(!name)throw new BadRequestException('Le nom est requis.');if(await this.prisma.productCategory.findFirst({where:{organizationId,name}}))throw new BadRequestException('Cette catégorie existe déjà.');const row=await this.prisma.productCategory.create({data:{organizationId,name}});await this.audit.record({organizationId,userId,action:'CREATE',entity:'ProductCategory',entityId:row.id,next:row,ip:request.ip,userAgent:request.headers['user-agent']});return row}
 async list(organizationId:string,search?:string,type?:string,active?:string){const where:any={organizationId};if(search)where.OR=[{name:{contains:search,mode:'insensitive'}},{sku:{contains:search,mode:'insensitive'}},{barcode:{contains:search,mode:'insensitive'}}];if(type)where.type=type;if(active!==undefined)where.active=active!=='false';return this.prisma.product.findMany({where,include:{category:true},orderBy:{name:'asc'}})}
 async get(organizationId:string,id:string){const row=await this.prisma.product.findFirst({where:{id,organizationId},include:{category:true}});if(!row)throw new NotFoundException('Produit ou service introuvable.');return row}
 async create(organizationId:string,userId:string,dto:CreateProductDto,request:any){const opening=Number(dto.stock??0);const data=await this.validate(organizationId,{...dto,stock:0});const row=await this.prisma.$transaction(async tx=>{const created=await tx.product.create({data});if(opening>0&&created.type==='PRODUCT')await this.inventory.openingForProduct(tx,organizationId,created.id,opening,userId);return created;});await this.audit.record({organizationId,userId,action:'CREATE',entity:'Product',entityId:row.id,next:row,ip:request.ip,userAgent:request.headers['user-agent']});return this.get(organizationId,row.id)}
 async update(organizationId:string,userId:string,id:string,dto:UpdateProductDto,request:any){const previous=await this.get(organizationId,id);if((dto as any).stock!==undefined&&Number((dto as any).stock)!==Number(previous.stock)) throw new BadRequestException('Le stock se modifie uniquement via un mouvement d’inventaire.');const data=await this.validate(organizationId,dto,true,id);delete data.stock;const row=await this.prisma.product.update({where:{id},data});await this.audit.record({organizationId,userId,action:'UPDATE',entity:'Product',entityId:id,previous,next:row,ip:request.ip,userAgent:request.headers['user-agent']});return this.get(organizationId,row.id)}
 async archive(organizationId:string,userId:string,id:string,request:any){const previous=await this.get(organizationId,id);const row=await this.prisma.product.update({where:{id},data:{active:false}});await this.audit.record({organizationId,userId,action:'ARCHIVE',entity:'Product',entityId:id,previous,next:row,ip:request.ip,userAgent:request.headers['user-agent']});return row}
 async lowStock(organizationId:string){const rows=await this.prisma.product.findMany({where:{organizationId,type:'PRODUCT',active:true,minimumStock:{gt:0}},orderBy:{name:'asc'}});return rows.filter(r=>Number(r.stock)<=Number(r.minimumStock))}
 private async validate(organizationId:string,dto:CreateProductDto,partial=false,id?:string){const name=dto.name?.trim();if(!name&&!partial)throw new BadRequestException('Le nom est requis.');if(dto.categoryId){const cat=await this.prisma.productCategory.findFirst({where:{id:dto.categoryId,organizationId}});if(!cat)throw new BadRequestException('Catégorie introuvable.');}if(dto.sku){const duplicate=await this.prisma.product.findFirst({where:{organizationId,sku:dto.sku.trim(),...(id?{id:{not:id}}:{})}});if(duplicate)throw new BadRequestException('Ce SKU existe déjà.');}const d:any={};for(const k of ['name','sku','barcode','description','categoryId','purchasePrice','sellingPrice','taxRate','unit','stock','minimumStock','supplier','active'])if((dto as any)[k]!==undefined)d[k]=typeof (dto as any)[k]==='string'?(dto as any)[k].trim():(dto as any)[k];if(dto.type!==undefined)d.type=dto.type;return d}
}
