'use client';
import {FormEvent,useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
type Expense={id:string;category:string;amount:number;incurredAt:string;description?:string;status:string};
export default function ExpensesPage(){
 const [rows,setRows]=useState<Expense[]>([]),[category,setCategory]=useState('AUTRE'),[amount,setAmount]=useState(''),[description,setDescription]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);const org=localStorage.getItem('sahlbiz_org')||'';const r=await fetch(API+'/expenses',{credentials:'include',headers:{'x-organization-id':org}});if(!r.ok){setError('Impossible de charger les dépenses.');setRows([])}else{const d=await r.json();setRows(Array.isArray(d)?d:d.items||[])}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();const org=localStorage.getItem('sahlbiz_org')||'';const r=await fetch(API+'/expenses',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org},body:JSON.stringify({category,amount:Number(amount),incurredAt:new Date().toISOString(),description,paymentMethod:'BANK'})});if(!r.ok){setError('Création impossible.');return}setAmount('');setDescription('');load()}
 const total=rows.reduce((s,x)=>s+Number(x.amount||0),0);
 return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Dépenses</h1><p className="text-sm text-gray-500">Dépenses enregistrées pour l’organisation active.</p></div><form onSubmit={create} className="grid md:grid-cols-4 gap-2 bg-white border rounded-xl p-4"><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Catégorie" className="border rounded-lg px-3 py-2"/><input required min="0.01" step="0.01" type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Montant" className="border rounded-lg px-3 py-2"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" className="border rounded-lg px-3 py-2"/><button className="rounded-lg bg-[var(--primary)] text-white px-4 py-2">Enregistrer</button></form>{error&&<div className="text-sm text-red-600">{error}</div>}<div className="bg-white border rounded-xl p-4"><div className="text-sm text-gray-500">Total chargé</div><div className="text-2xl font-bold">{total.toLocaleString('fr-MA')} MAD</div></div><div className="bg-white border rounded-xl overflow-hidden">{loading?<div className="p-8 text-center text-gray-500">Chargement…</div>:rows.length===0?<div className="p-8 text-center text-gray-500">Aucune dépense.</div>:<table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Catégorie</th><th className="p-3 text-right">Montant</th><th className="p-3 text-left">Statut</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3">{new Date(x.incurredAt).toLocaleDateString('fr-MA')}</td><td className="p-3">{x.category}</td><td className="p-3 text-right">{Number(x.amount).toLocaleString('fr-MA')} MAD</td><td className="p-3">{x.status}</td></tr>)}</tbody></table>}</div></section>
}