'use client';
import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeftRight,Boxes,Plus,RefreshCw,SlidersHorizontal,Truck} from 'lucide-react';

type Org={id:string;name:string;role:string};
type Warehouse={id:string;name:string;code:string;isDefault:boolean;active:boolean};
type Stock={warehouseId:string;productId:string;quantity:number;minimumStock:number;warehouse:{name:string};product:{name:string;sku?:string;unit:string}};
type Movement={id:string;quantity:number;type:string;occurredAt:string;warehouse:{name:string};product:{name:string};note?:string};
const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
const types:{value:string;label:string}[]=[{value:'OPENING',label:'Ouverture'},{value:'RECEIPT',label:'Réception'},{value:'SALE_ISSUE',label:'Sortie vente'},{value:'ADJUSTMENT_IN',label:'Ajustement +'},{value:'ADJUSTMENT_OUT',label:'Ajustement -'},{value:'TRANSFER_IN',label:'Transfert entrant'},{value:'TRANSFER_OUT',label:'Transfert sortant'}];
export default function Inventory(){
 const [orgs,setOrgs]=useState<Org[]>([]),[org,setOrg]=useState(''),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[warehouseId,setWarehouseId]=useState(''),[stock,setStock]=useState<Stock[]>([]),[movements,setMovements]=useState<Movement[]>([]),[products,setProducts]=useState<any[]>([]),[productId,setProductId]=useState(''),[qty,setQty]=useState(''),[direction,setDirection]=useState<'IN'|'OUT'>('IN'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[activeTab,setActiveTab]=useState<'stock'|'movements'>('stock'),[filterType,setFilterType]=useState(''),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function init(){const r=await fetch(`${API}/auth/me`,{credentials:'include'});if(!r.ok)return;const d=await r.json();const list=d.organizations.map((m:any)=>({id:m.organizationId,name:m.organization.name,role:m.role}));setOrgs(list);const saved=localStorage.getItem('sahlbiz_org');setOrg(list.some((x:any)=>x.id===saved)?saved:list[0]?.id||'')}
 async function load(){if(!org)return;setLoading(true);setError('');const h={'x-organization-id':org};const [w,s,m,p]=await Promise.all([fetch(`${API}/inventory/warehouses`,{credentials:'include',headers:h}),fetch(`${API}/inventory/stock${warehouseId?`?warehouseId=${warehouseId}`:''}`,{credentials:'include',headers:h}),fetch(`${API}/inventory/movements${warehouseId?`?warehouseId=${warehouseId}${filterType?`&type=${filterType}`:''}`:filterType?`?type=${filterType}`:''}`,{credentials:'include',headers:h}),fetch(`${API}/products?type=PRODUCT&active=true`,{credentials:'include',headers:h})]);if(w.ok){const x=await w.json();setWarehouses(x);if(!warehouseId)setWarehouseId(x.find((a:any)=>a.isDefault)?.id||x[0]?.id||'')}if(s.ok)setStock(await s.json());if(m.ok)setMovements(await m.json());if(p.ok)setProducts(await p.json());setLoading(false)}
 useEffect(()=>{init()},[]);useEffect(()=>{if(org){localStorage.setItem('sahlbiz_org',org);load()}},[org]);useEffect(()=>{if(org)load()},[warehouseId,filterType]);
 async function post(path:string,body:any){const r=await fetch(`${API}/inventory/${path}`,{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org},body:JSON.stringify(body)});if(!r.ok){const t=await r.text();setError(t||'Action impossible.');return false}setQty('');setNote('');await load();return true}
 async function adjust(e:FormEvent){e.preventDefault();if(!warehouseId||!productId)return;await post('adjustments',{warehouseId,productId,direction,quantity:Number(qty),note:note||undefined})}
 async function transfer(e:FormEvent){e.preventDefault();if(!from||!to||!productId)return;await post('transfers',{fromWarehouseId:from,toWarehouseId:to,productId,quantity:Number(qty),note:note||undefined})}
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-gray-500">Opérations</p><h1 className="text-2xl font-bold">Inventaire</h1><p className="text-sm text-gray-500 mt-1">Stock multi-dépôts, mouvements traçables et sorties liées aux factures.</p></div><div className="flex gap-2"><select value={org} onChange={e=>setOrg(e.target.value)} className="border rounded-lg px-3 py-2">{orgs.map(o=><option key={o.id} value={o.id}>{o.name} · {o.role}</option>)}</select><button onClick={load} className="border rounded-lg p-2" title="Actualiser"><RefreshCw size={18}/></button></div></div>{error&&<div className="bg-red-50 text-red-700 border border-red-100 rounded-lg p-3 text-sm">{error}</div>}
 <div className="grid md:grid-cols-3 gap-4"><div className="bg-white border rounded-xl p-5"><div className="text-sm text-gray-500">Dépôts actifs</div><div className="text-2xl font-bold mt-1">{warehouses.filter(w=>w.active).length}</div></div><div className="bg-white border rounded-xl p-5"><div className="text-sm text-gray-500">Lignes de stock</div><div className="text-2xl font-bold mt-1">{stock.length}</div></div><div className="bg-white border rounded-xl p-5"><div className="text-sm text-gray-500">Mouvements récents</div><div className="text-2xl font-bold mt-1">{movements.length}</div></div></div>
 <div className="grid xl:grid-cols-2 gap-5"><form onSubmit={adjust} className="bg-white border rounded-xl p-5"><div className="font-semibold flex items-center gap-2"><SlidersHorizontal size={17}/>Ajuster le stock</div><div className="grid md:grid-cols-2 gap-3 mt-4"><select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} className="border rounded-lg p-2.5">{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select value={productId} onChange={e=>setProductId(e.target.value)} className="border rounded-lg p-2.5"><option value="">Choisir un produit</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}{p.sku?` · ${p.sku}`:''}</option>)}</select><select value={direction} onChange={e=>setDirection(e.target.value as any)} className="border rounded-lg p-2.5"><option value="IN">Entrée</option><option value="OUT">Sortie</option></select><input required type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Quantité" className="border rounded-lg p-2.5"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Motif / note" className="border rounded-lg p-2.5 md:col-span-2"/><button className="bg-[var(--primary)] text-white rounded-lg px-4 py-2 inline-flex justify-center items-center gap-2"><Plus size={16}/>Enregistrer le mouvement</button></div></form>
 <form onSubmit={transfer} className="bg-white border rounded-xl p-5"><div className="font-semibold flex items-center gap-2"><ArrowLeftRight size={17}/>Transférer entre dépôts</div><div className="grid md:grid-cols-2 gap-3 mt-4"><select required value={from} onChange={e=>setFrom(e.target.value)} className="border rounded-lg p-2.5"><option value="">Dépôt source</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select required value={to} onChange={e=>setTo(e.target.value)} className="border rounded-lg p-2.5"><option value="">Dépôt destination</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select required value={productId} onChange={e=>setProductId(e.target.value)} className="border rounded-lg p-2.5"><option value="">Choisir un produit</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Quantité" className="border rounded-lg p-2.5"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Motif / note" className="border rounded-lg p-2.5 md:col-span-2"/><button className="border rounded-lg px-4 py-2 inline-flex justify-center items-center gap-2"><Truck size={16}/>Transférer</button></div></form></div>
 <div className="bg-white border rounded-xl overflow-hidden"><div className="p-4 border-b flex flex-wrap gap-2 items-center"><button onClick={()=>setActiveTab('stock')} className={`px-3 py-2 rounded-lg text-sm ${activeTab==='stock'?'bg-gray-100 font-semibold':''}`}>Stock par dépôt</button><button onClick={()=>setActiveTab('movements')} className={`px-3 py-2 rounded-lg text-sm ${activeTab==='movements'?'bg-gray-100 font-semibold':''}`}>Mouvements</button>{activeTab==='stock'?<select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} className="ml-auto border rounded-lg px-3 py-2 text-sm"><option value="">Tous les dépôts</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select>:<select value={filterType} onChange={e=>setFilterType(e.target.value)} className="ml-auto border rounded-lg px-3 py-2 text-sm"><option value="">Tous les mouvements</option>{types.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select>}</div>{loading?<div className="p-8 text-sm text-gray-500">Chargement…</div>:activeTab==='stock'?<table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr><th className="text-left p-3">Produit</th><th className="text-left p-3">Dépôt</th><th className="text-right p-3">Disponible</th><th className="text-right p-3">Minimum</th></tr></thead><tbody>{stock.map(r=><tr key={r.warehouseId+r.productId} className="border-b last:border-0"><td className="p-3"><div className="font-medium">{r.product.name}</div><div className="text-xs text-gray-500">{r.product.sku||'—'}</div></td><td className="p-3">{r.warehouse.name}</td><td className={`p-3 text-right font-semibold ${r.quantity<=r.minimumStock&&r.minimumStock>0?'text-red-600':''}`}>{r.quantity} {r.product.unit}</td><td className="p-3 text-right">{r.minimumStock} {r.product.unit}</td></tr>)}{stock.length===0&&<tr><td colSpan={4} className="p-10 text-center text-gray-500"><Boxes className="mx-auto mb-2 text-gray-300"/>Aucun stock enregistré.</td></tr>}</tbody></table>:<table className="w-full text-sm"><thead className="bg-gray-50 border-b"><tr><th className="text-left p-3">Date</th><th className="text-left p-3">Produit</th><th className="text-left p-3">Dépôt</th><th className="text-left p-3">Type</th><th className="text-right p-3">Qté</th></tr></thead><tbody>{movements.map(m=><tr key={m.id} className="border-b last:border-0"><td className="p-3">{new Date(m.occurredAt).toLocaleString('fr-MA')}</td><td className="p-3">{m.product.name}</td><td className="p-3">{m.warehouse.name}</td><td className="p-3">{types.find(t=>t.value===m.type)?.label||m.type}</td><td className="p-3 text-right">{m.quantity}</td></tr>)}{movements.length===0&&<tr><td colSpan={5} className="p-10 text-center text-gray-500">Aucun mouvement.</td></tr>}</tbody></table>}</div></div>;
}
