'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Building2,CheckSquare,FileText,Package,Receipt,Search as SearchIcon,Users,Wallet,BriefcaseBusiness,Warehouse as WarehouseIcon} from 'lucide-react';

const API=process.env.NEXT_PUBLIC_API_URL||'/api/v1';
const labels: Record<string, string> = {customer:'Client',product:'Produit',service:'Service',quote:'Devis',invoice:'Facture',project:'Projet',task:'Tâche',supplier:'Fournisseur',supplier_bill:'Facture fournisseur',expense:'Dépense',document:'Document',warehouse:'Entrepôt'};
const icons:any={customer:Users,product:Package,service:Package,quote:FileText,invoice:Receipt,project:BriefcaseBusiness,task:CheckSquare,supplier:Building2,supplier_bill:Receipt,expense:Wallet,document:FileText,warehouse:WarehouseIcon};
export default function SearchPage(){
 const [q,setQ]=useState(''); const [data,setData]=useState<any>({items:[],total:0}); const [loading,setLoading]=useState(false);
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get('q')||'';setQ(value);},[]);
 useEffect(()=>{if(q.trim().length<2){setData({items:[],total:0});return;} const t=setTimeout(async()=>{setLoading(true);try{const org=localStorage.getItem('sahlbiz_org')||'';const r=await fetch(`${API}/search?q=${encodeURIComponent(q.trim())}`,{credentials:'include',headers:{'x-organization-id':org}});setData(await r.json())}finally{setLoading(false)}},250);return()=>clearTimeout(t)},[q]);
 const grouped=useMemo(()=>{const m:any={};for(const x of data.items||[])(m[x.type]??=[]).push(x);return m},[data]);
 function submit(e:any){e.preventDefault();history.replaceState(null,'',`/search?q=${encodeURIComponent(q)}`)}
 return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Recherche globale</h1><p className="text-sm text-gray-500 mt-1">Clients, ventes, produits, projets, documents et finance.</p></div><form onSubmit={submit} className="relative max-w-3xl"><SearchIcon className="absolute left-3 top-3 text-gray-400" size={19}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher un client, devis, facture, produit…" className="w-full rounded-xl border border-gray-200 bg-white py-3 pl-10 pr-4 outline-none focus:ring-2 focus:ring-[var(--primary)]"/></form>{loading&&<div className="text-sm text-gray-500">Recherche…</div>}{q.trim().length<2&&!loading&&<div className="rounded-xl border border-dashed border-gray-300 bg-white p-10 text-center text-sm text-gray-500">Saisissez au moins 2 caractères.</div>}{q.trim().length>=2&&!loading&&data.total===0&&<div className="rounded-xl border border-dashed border-gray-300 bg-white p-10 text-center text-sm text-gray-500">Aucun résultat pour « {q} ».</div>}{q.trim().length>=2&&!loading&&data.total>0&&<div className="space-y-5">{Object.entries(grouped).map(([type,items]:any)=><section key={type}><div className="flex items-center gap-2 mb-2"><span className="text-xs font-semibold uppercase tracking-wide text-gray-400">{labels[type]||type}</span><span className="text-xs text-gray-400">{items.length}</span></div><div className="rounded-xl border border-gray-200 bg-white divide-y">{items.map((x:any)=>{const Icon=icons[x.type]||FileText;return <Link key={x.id} href={x.href} className="flex items-center gap-4 px-4 py-3 hover:bg-gray-50"><div className="w-9 h-9 rounded-lg bg-gray-100 flex items-center justify-center"><Icon size={17}/></div><div className="min-w-0 flex-1"><div className="font-medium text-sm truncate">{x.title}</div><div className="text-xs text-gray-500 truncate">{x.subtitle}</div></div><ArrowRight size={16} className="text-gray-400"/></Link>})}</div></section>)}</div>}</div>
}
