'use client';
import {apiFetch,getOrganizationId,setOrganizationId} from '../../../lib/api-client';
import {FormEvent,useEffect,useState} from 'react';
type Customer={id:string;name:string;type:string;email?:string;phone?:string;ice?:string};
export default function CustomersPage(){
 const [rows,setRows]=useState<Customer[]>([]),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[ice,setIce]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const org=getOrganizationId()||'';const r=await apiFetch(+'/customers',{credentials:'include',headers:{'x-organization-id':org}});if(!r.ok){setError('Impossible de charger les clients.');setRows([])}else{const d=await r.json();setRows(Array.isArray(d)?d:d.items||[])}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();const org=getOrganizationId()||'';const r=await apiFetch(+'/customers',{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-organization-id':org},body:JSON.stringify({name,email:email||undefined,phone:phone||undefined,ice:ice||undefined,type:'COMPANY'})});if(!r.ok){setError('Création impossible.');return}setName('');setEmail('');setPhone('');setIce('');load()}
 return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Clients</h1><p className="text-sm text-gray-500">Clients de l’organisation active.</p></div><form onSubmit={create} className="grid md:grid-cols-5 gap-2 bg-white border rounded-xl p-4"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nom" className="border rounded-lg px-3 py-2"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email" className="border rounded-lg px-3 py-2"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Téléphone" className="border rounded-lg px-3 py-2"/><input value={ice} onChange={e=>setIce(e.target.value)} placeholder="ICE" className="border rounded-lg px-3 py-2"/><button className="rounded-lg bg-[var(--primary)] text-white px-4 py-2">Ajouter</button></form>{error&&<div className="text-sm text-red-600">{error}</div>}<div className="bg-white border rounded-xl overflow-hidden">{loading?<div className="p-8 text-center text-gray-500">Chargement…</div>:rows.length===0?<div className="p-8 text-center text-gray-500">Aucun client.</div>:<table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Client</th><th className="p-3 text-left">ICE</th><th className="p-3 text-left">Email</th><th className="p-3 text-left">Téléphone</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-t"><td className="p-3 font-medium">{c.name}</td><td className="p-3">{c.ice||'—'}</td><td className="p-3">{c.email||'—'}</td><td className="p-3">{c.phone||'—'}</td></tr>)}</tbody></table>}</div></section>
}